"""
Finance Adapters Module

Exports all finance Django database adapters.
"""

from .transaction_adapter import (
    django_transaction_to_data,
    get_school_by_lookup,
    get_bank_account,
    get_transaction_type,
    get_payment_method,
    get_student,
    get_academic_year,
    create_transaction_in_db,
    update_transaction_in_db,
    update_transaction_status_in_db,
    delete_transaction_from_db,
    delete_transactions_by_reference_from_db,
    get_transaction_by_id,
    get_student_pending_transactions_count,
    get_student_approved_balance,
    get_account_balance,
    get_transactions_by_filters,
    create_bulk_transactions_in_db,
)

from .fee_adapter import (
    django_general_fee_to_data,
    django_section_fee_to_data,
    get_general_fee_by_id,
    get_section_fee_by_id,
    get_section_by_id,
    create_general_fee_in_db,
    update_general_fee_in_db,
    delete_general_fee_from_db,
    get_general_fees_by_school,
    get_section_fee_count_for_general_fee,
    create_section_fee_in_db,
    create_or_update_section_fee_in_db,
    update_section_fee_in_db,
    delete_section_fee_from_db,
    get_section_fees_by_school,
    get_section_fees_by_filters,
    get_active_sections_by_school,
    apply_fee_to_all_sections,
)

from .supporting_adapter import (
    django_bank_account_to_data,
    django_payment_method_to_data,
    django_currency_to_data,
    django_transaction_type_to_data,
    create_bank_account_in_db,
    update_bank_account_in_db,
    delete_bank_account_from_db,
    get_bank_account_by_id,
    get_bank_accounts_by_school,
    get_bank_account_transaction_count,
    check_bank_account_number_exists,
    create_payment_method_in_db,
    update_payment_method_in_db,
    delete_payment_method_from_db,
    get_payment_method_by_id,
    get_payment_methods_by_school,
    create_currency_in_db,
    update_currency_in_db,
    delete_currency_from_db,
    get_currency_by_id,
    get_currencies_by_school,
    check_currency_code_exists,
    create_transaction_type_in_db,
    update_transaction_type_in_db,
    delete_transaction_type_from_db,
    get_transaction_type_by_id,
    get_transaction_types_by_school,
    check_transaction_type_code_exists,
)

__all__ = [
    # Transaction adapter
    'django_transaction_to_data',
    'get_school_by_lookup',
    'get_bank_account',
    'get_transaction_type',
    'get_payment_method',
    'get_student',
    'get_academic_year',
    'create_transaction_in_db',
    'update_transaction_in_db',
    'update_transaction_status_in_db',
    'delete_transaction_from_db',
    'delete_transactions_by_reference_from_db',
    'get_transaction_by_id',
    'get_student_pending_transactions_count',
    'get_student_approved_balance',
    'get_account_balance',
    'get_transactions_by_filters',
    'create_bulk_transactions_in_db',
    
    # Fee adapter
    'django_general_fee_to_data',
    'django_section_fee_to_data',
    'get_general_fee_by_id',
    'get_section_fee_by_id',
    'get_section_by_id',
    'create_general_fee_in_db',
    'update_general_fee_in_db',
    'delete_general_fee_from_db',
    'get_general_fees_by_school',
    'get_section_fee_count_for_general_fee',
    'create_section_fee_in_db',
    'create_or_update_section_fee_in_db',
    'update_section_fee_in_db',
    'delete_section_fee_from_db',
    'get_section_fees_by_school',
    'get_section_fees_by_filters',
    'get_active_sections_by_school',
    'apply_fee_to_all_sections',
    
    # Supporting entities adapter
    'django_bank_account_to_data',
    'django_payment_method_to_data',
    'django_currency_to_data',
    'django_transaction_type_to_data',
    'create_bank_account_in_db',
    'update_bank_account_in_db',
    'delete_bank_account_from_db',
    'get_bank_account_by_id',
    'get_bank_accounts_by_school',
    'get_bank_account_transaction_count',
    'check_bank_account_number_exists',
    'create_payment_method_in_db',
    'update_payment_method_in_db',
    'delete_payment_method_from_db',
    'get_payment_method_by_id',
    'get_payment_methods_by_school',
    'create_currency_in_db',
    'update_currency_in_db',
    'delete_currency_from_db',
    'get_currency_by_id',
    'get_currencies_by_school',
    'check_currency_code_exists',
    'create_transaction_type_in_db',
    'update_transaction_type_in_db',
    'delete_transaction_type_from_db',
    'get_transaction_type_by_id',
    'get_transaction_types_by_school',
    'check_transaction_type_code_exists',
]
