# Generated by Django 5.2.11 on 2026-05-02 00:57

import common.status
import core.validators
import django.db.models.deletion
import tenant_users.permissions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Optional username for login",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("id_number", models.CharField(max_length=50, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("global", "Global"),
                            ("staff", "Staff"),
                            ("parent", "Parent"),
                            ("other", "Other"),
                        ],
                        default=common.status.UserAccountType["OTHER"],
                        help_text="User type: GLOBAL (system admin), TENANT (staff/student), or PARENT",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Superadmin"),
                            ("admin", "Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("viewer", "Viewer"),
                            ("registrar", "Registrar"),
                            ("data_entry", "Data_entry"),
                            ("parent", "Parent"),
                            ("accountant", "Accountant"),
                        ],
                        default="viewer",
                        help_text="User role: VIEWER (default), ADMIN, TEACHER, STUDENT, PARENT, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reset", "Reset"),
                            ("created", "Created"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        help_text="User status: ACTIVE (default), INACTIVE, SUSPENDED, DELETED, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="User profile photo (storage backend handles tenant isolation)",
                        null=True,
                        upload_to="users",
                        validators=[core.validators.ValidateImageFile],
                    ),
                ),
                (
                    "last_password_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last password updated timestamp",
                        null=True,
                    ),
                ),
                (
                    "is_default_password",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user is using the default password. This is used to determine if the user needs to change their password on login.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups for Django permission system",
                        related_name="school_users",
                        to="auth.group",
                    ),
                ),
                (
                    "tenants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The tenants this user belongs to.",
                        related_name="user_set",
                        to="core.tenant",
                        verbose_name="tenants",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Direct permissions for user",
                        related_name="school_users",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
            bases=(
                models.Model,
                tenant_users.permissions.models.PermissionsMixinFacade,
            ),
        ),
        migrations.CreateModel(
            name="RoleDefaultPrivilege",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Superadmin"),
                            ("admin", "Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("viewer", "Viewer"),
                            ("registrar", "Registrar"),
                            ("data_entry", "Data_entry"),
                            ("parent", "Parent"),
                            ("accountant", "Accountant"),
                        ],
                        help_text="Role this privilege applies to",
                        max_length=20,
                    ),
                ),
                (
                    "privilege_code",
                    models.CharField(
                        help_text="Privilege code (e.g., STUDENTS_MANAGE)",
                        max_length=50,
                    ),
                ),
                (
                    "applies_to_account_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Account types this applies to (e.g., ['staff', 'student']). Empty = all types.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Description of why this privilege is granted to this role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Default Privilege",
                "verbose_name_plural": "Role Default Privileges",
                "db_table": "user_role_default_privilege",
                "ordering": ["role", "privilege_code"],
                "indexes": [
                    models.Index(fields=["role"], name="user_role_d_role_d58241_idx"),
                    models.Index(
                        fields=["privilege_code"], name="user_role_d_privile_fc3497_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "privilege_code"),
                        name="user_uniq_role_privilege",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecialPrivilege",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Privilege code (e.g., GRADING_APPROVE, TRANSACTION_DELETE)",
                        max_length=50,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Privilege automatically revoked after this date (optional)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Reason/notes for granting (e.g., 'Temporary grading approval for Q3')",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who granted this privilege",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_privileges_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who holds this privilege",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_privileges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Privilege",
                "verbose_name_plural": "Special Privileges",
                "db_table": "user_special_privilege",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_specia_user_id_fbf40b_idx"
                    ),
                    models.Index(fields=["code"], name="user_specia_code_b994f6_idx"),
                    models.Index(
                        fields=["expires_at"], name="user_specia_expires_c551b3_idx"
                    ),
                    models.Index(
                        fields=["granted_at"], name="user_specia_granted_8a34a5_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "code"), name="user_uniq_special_privilege"
                    )
                ],
            },
        ),
    ]
