# Generated by Django 5.2.10 on 2026-08-02 22:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rename_tenant_owner_activation_indexes"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentralAuthSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key_hash", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="central_auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_central_auth_session",
            },
        ),
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("require_pkce", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "auth_oauth_client",
                "indexes": [
                    models.Index(
                        fields=["client_id"], name="auth_oauth__client__ab96bc_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="auth_oauth__is_acti_e44355_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state_hash", models.CharField(db_index=True, max_length=128)),
                ("redirect_uri", models.URLField(max_length=500)),
                ("code_challenge", models.CharField(max_length=255)),
                (
                    "code_challenge_method",
                    models.CharField(default="S256", max_length=20),
                ),
                ("return_to", models.CharField(default="/", max_length=500)),
                ("requested_scopes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_requests",
                        to="core.tenant",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_requests",
                        to="users.oauthclient",
                    ),
                ),
            ],
            options={
                "db_table": "auth_authorization_request",
            },
        ),
        migrations.CreateModel(
            name="AuthorizationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128, unique=True)),
                ("redirect_uri", models.URLField(max_length=500)),
                ("code_challenge", models.CharField(max_length=255)),
                (
                    "code_challenge_method",
                    models.CharField(default="S256", max_length=20),
                ),
                ("requested_scopes", models.JSONField(blank=True, default=list)),
                ("return_to", models.CharField(default="/", max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_codes",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "auth_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorization_codes",
                        to="users.centralauthsession",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_codes",
                        to="users.oauthclient",
                    ),
                ),
            ],
            options={
                "db_table": "auth_authorization_code",
            },
        ),
        migrations.CreateModel(
            name="AuthenticationAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_audit_events",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_audit_events",
                        to="users.oauthclient",
                    ),
                ),
            ],
            options={
                "db_table": "auth_audit_event",
            },
        ),
        migrations.CreateModel(
            name="OAuthRedirectURI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("redirect_uri", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redirect_uris",
                        to="users.oauthclient",
                    ),
                ),
            ],
            options={
                "db_table": "auth_oauth_redirect_uri",
            },
        ),
        migrations.CreateModel(
            name="RefreshTokenFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("reuse_detected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "global_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refresh_token_families",
                        to="users.centralauthsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_token_families",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_token_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_refresh_token_family",
            },
        ),
        migrations.CreateModel(
            name="TenantSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key_hash", models.CharField(max_length=128, unique=True)),
                ("membership_id", models.CharField(blank=True, max_length=100)),
                ("roles", models.JSONField(blank=True, default=list)),
                (
                    "permission_version",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "global_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_sessions",
                        to="users.centralauthsession",
                    ),
                ),
                (
                    "refresh_token_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_sessions",
                        to="users.refreshtokenfamily",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_sessions",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_tenant_session",
            },
        ),
        migrations.CreateModel(
            name="SessionRevocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("global", "Global"),
                            ("token_family", "Token Family"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "central_auth_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revocations",
                        to="users.centralauthsession",
                    ),
                ),
                (
                    "refresh_token_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revocations",
                        to="users.refreshtokenfamily",
                    ),
                ),
                (
                    "tenant_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revocations",
                        to="users.tenantsession",
                    ),
                ),
            ],
            options={
                "db_table": "auth_session_revocation",
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("reuse_detected", models.BooleanField(default=False)),
                (
                    "rotated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rotated_to",
                        to="users.refreshtoken",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="users.refreshtokenfamily",
                    ),
                ),
                (
                    "tenant_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="users.tenantsession",
                    ),
                ),
            ],
            options={
                "db_table": "auth_refresh_token",
            },
        ),
        migrations.AddIndex(
            model_name="centralauthsession",
            index=models.Index(
                fields=["user", "revoked_at"], name="auth_centra_user_id_4bbccc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="centralauthsession",
            index=models.Index(
                fields=["expires_at"], name="auth_centra_expires_5a9d5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authorizationrequest",
            index=models.Index(
                fields=["state_hash"], name="auth_author_state_h_65c695_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authorizationrequest",
            index=models.Index(
                fields=["expires_at", "consumed_at"],
                name="auth_author_expires_fa89d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authorizationcode",
            index=models.Index(
                fields=["code_hash"], name="auth_author_code_ha_7e0efd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authorizationcode",
            index=models.Index(
                fields=["expires_at", "consumed_at"],
                name="auth_author_expires_7bc9de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authorizationcode",
            index=models.Index(
                fields=["tenant", "user"], name="auth_author_tenant__8024d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationauditevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="auth_audit__event_t_9c1c96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationauditevent",
            index=models.Index(
                fields=["user", "created_at"], name="auth_audit__user_id_0c1851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationauditevent",
            index=models.Index(
                fields=["tenant", "created_at"], name="auth_audit__tenant__f8e974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oauthredirecturi",
            index=models.Index(
                fields=["client", "is_active"], name="auth_oauth__client__6c2835_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthredirecturi",
            constraint=models.UniqueConstraint(
                fields=("client", "redirect_uri"), name="auth_oauth_redirect_uri_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtokenfamily",
            index=models.Index(
                fields=["user", "tenant", "revoked_at"],
                name="auth_refres_user_id_f890f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantsession",
            index=models.Index(
                fields=["global_session", "revoked_at"],
                name="auth_tenant_global__09157a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantsession",
            index=models.Index(
                fields=["tenant", "user", "revoked_at"],
                name="auth_tenant_tenant__a5bf18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantsession",
            index=models.Index(
                fields=["expires_at"], name="auth_tenant_expires_41be63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionrevocation",
            index=models.Index(
                fields=["scope", "created_at"], name="auth_sessio_scope_3f6997_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["token_hash"], name="auth_refres_token_h_41144c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["family", "revoked_at"], name="auth_refres_family__bf7447_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["expires_at"], name="auth_refres_expires_6976f5_idx"
            ),
        ),
    ]
