# Generated by Django 5.2.17 on 2026-09-06 13:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_security_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="User profile photo (storage backend handles tenant isolation)",
                null=True,
                upload_to="users",
                validators=[core.validators.ValidateImageFile()],
            ),
        ),
    ]
