# Generated by Django 5.2.17 on 2026-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_schooluseraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluseraccess',
            name='instructions_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schooluseraccess',
            name='instructions_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
