# Generated by Django 5.2.17 on 2026-10-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_merge_parent_and_mfa_histories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsession',
            name='device_metadata',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
    ]
