# Generated by Django 5.2.10 on 2026-06-17 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="billingseat",
            new_name="billing_sea_tenant__3ae46e_idx",
            old_name="billing_seat_tenant_year_void_idx",
        ),
        migrations.RenameIndex(
            model_name="billingseat",
            new_name="billing_sea_tenant__d0514c_idx",
            old_name="billing_seat_tenant_enroll_idx",
        ),
    ]
