# Generated by Django 5.2.11 on 2026-03-05 05:02

import common.status
import core.validators
import django.core.validators
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                            ("holiday", "Holiday"),
                        ],
                        default=common.status.AttendanceStatus["PRESENT"],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_enrolled", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "enrolled_as",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("transferred", "Transferred"),
                            ("returning", "Returning"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollment",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150)),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default=None, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reset", "Reset"),
                            ("created", "Created"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=1,
                        size=[300, 300],
                        upload_to="photos",
                        validators=[core.validators.ValidateImageFile],
                    ),
                ),
                (
                    "prev_id_number",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "date_of_graduation",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("entry_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "entry_as",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("returning", "Returning"),
                            ("transferred", "Transferred"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "withdrawal_reason",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("school_code", models.PositiveSmallIntegerField()),
                ("student_seq", models.PositiveIntegerField()),
                (
                    "id_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=6,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^\\d{6}$")],
                    ),
                ),
                (
                    "user_account_id_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reference to User.id_number in public schema (avoid cross-schema FK)",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "student",
                "ordering": ["school_code", "student_seq"],
            },
        ),
        migrations.CreateModel(
            name="StudentConcession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concession_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("flat", "Flat Value")],
                        max_length=20,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("entire_bill", "Entire Bill"),
                            ("tuition", "Tuition Only"),
                            ("other_fees", "Other Fees Only"),
                        ],
                        default="entire_bill",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage value (e.g. 10 for 10%) or flat amount depending on concession_type",
                        max_digits=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Computed total concession amount based on target and value",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Student Concession",
                "verbose_name_plural": "Student Concessions",
                "db_table": "student_concession",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("guardian", "Guardian"),
                            ("sibling", "Sibling"),
                            ("relative", "Relative"),
                            ("family_friend", "Family Friend"),
                            ("neighbor", "Neighbor"),
                            ("teacher", "Teacher"),
                            ("counselor", "Counselor"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default=None, null=True)),
                ("is_emergency", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("photo", models.URLField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "Student Contact",
                "verbose_name_plural": "Student Contacts",
                "db_table": "student_contact",
                "ordering": ["-is_primary", "-is_emergency", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollmentBill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tuition", "Tuition"),
                            ("fee", "Fee"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "Student Bill",
                "verbose_name_plural": "Student Bills",
                "db_table": "enrollment_bill",
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("stepfather", "Stepfather"),
                            ("stepmother", "Stepmother"),
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("legal_guardian", "Legal Guardian"),
                            ("foster_parent", "Foster Parent"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default=None, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "workplace",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("photo", models.URLField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                (
                    "user_account_id_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reference to User.id_number in public schema (avoid cross-schema FK)",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Guardian",
                "verbose_name_plural": "Student Guardians",
                "db_table": "student_guardian",
                "ordering": ["-is_primary", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentPaymentSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_plan",
                    models.JSONField(
                        default=list,
                        help_text="Pre-calculated payment plan array (expensive calculation: iterates installments, matches payments)",
                    ),
                ),
                (
                    "payment_status",
                    models.JSONField(
                        default=dict,
                        help_text="Pre-calculated payment status dict (expensive calculation: iterates installments, checks overdue)",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Pre-calculated total paid (requires transaction join, used in payment_plan calculations)",
                        max_digits=10,
                    ),
                ),
                (
                    "last_calculated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last calculation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Payment Summary",
                "verbose_name_plural": "Student Payment Summaries",
                "db_table": "student_payment_summary",
            },
        ),
        migrations.CreateModel(
            name="StudentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_seq", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Student Sequence",
                "verbose_name_plural": "Student Sequences",
                "db_table": "student_sequence",
            },
        ),
    ]
