# Generated by Django 5.2.11 on 2026-03-15 02:32

import common.status
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_remove_attendance_marking_period"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance_marking_714e2a_idx",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                    ("sick", "Sick"),
                    ("on_leave", "On_leave"),
                    ("holiday", "Holiday"),
                ],
                default=common.status.AttendanceStatus["PRESENT"],
                max_length=20,
            ),
        ),
    ]
