# Generated by Django 5.2.10 on 2026-06-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_enrollment_status_enrolled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("enrolled", "Enrolled"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
