# Generated by Django 5.2.10 on 2026-06-11 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_historical_grade_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="historicalgraderecord",
            new_name="historical__student_df688f_idx",
            old_name="historical__student_6f1a2b_idx",
        ),
        migrations.RenameIndex(
            model_name="historicalgraderecord",
            new_name="historical__academi_7e13e5_idx",
            old_name="historical__academi_7c3d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="historicalgraderecord",
            new_name="historical__grade_l_6c0e96_idx",
            old_name="historical__grade_l_8e5f6a_idx",
        ),
        migrations.RemoveField(
            model_name="historicalgraderecord",
            name="meta",
        ),
        migrations.AddField(
            model_name="historicalgraderecord",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicalgraderecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraderecord",
            name="credits",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=None, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraderecord",
            name="final_letter",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="historicalgraderecord",
            name="final_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraderecord",
            name="notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalgraderecord",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgraderecord",
            name="verified_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
