# Generated by Django 5.2.10 on 2026-06-11 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0009_alter_academicyear_options_and_more"),
        ("students", "0010_historical_grade_period_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="historicalgraderecord",
            index=models.Index(
                fields=["period_end_date"], name="historical__period__c06408_idx"
            ),
        ),
    ]
