# Generated by Django 5.2.11 on 2026-07-23 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_default_action_types(apps, schema_editor):
    DisciplinaryActionType = apps.get_model("students", "DisciplinaryActionType")

    defaults = [
        ("verbal-warning", "Verbal Warning", "informal", "Staff member verbally corrects the student's behavior."),
        ("counseling-session", "Counseling Session", "informal", "Student meets with counselor or administrator."),
        ("teacher-conference", "Teacher Conference", "informal", "Teacher discusses the incident with the student."),
        ("parent-notification", "Parent Notification", "informal", "Parent or guardian is formally notified."),
        ("parent-conference", "Parent Conference", "informal", "Formal meeting with guardian and school staff."),
        ("written-warning", "Written Warning", "corrective", "Official warning recorded in the student's history."),
        ("behavior-reflection", "Behavior Reflection", "corrective", "Student writes a reflection about the incident."),
        ("apology-required", "Apology Required", "corrective", "Student provides verbal or written apology."),
        ("behavior-contract", "Behavior Contract", "corrective", "Student signs agreement of expected behavior."),
        ("restorative-conference", "Restorative Conference", "corrective", "Structured repair-focused discussion between parties."),
        ("restitution", "Restitution", "corrective", "Student repairs or replaces damaged property when appropriate."),
        ("loss-of-privileges", "Loss of Privileges", "restrictive", "Temporary removal from specified privileges."),
        ("classroom-removal", "Classroom Removal", "restrictive", "Student removed from a specific class for a period."),
        ("assigned-seating", "Assigned Seating", "restrictive", "Student moved to a designated supervised seat."),
        ("detention", "Detention", "restrictive", "Student remains for supervised detention period."),
        ("community-service", "Community Service", "restrictive", "Student performs supervised school service."),
        ("assignment-make-up", "Assignment Make-Up Required", "academic", "Student must redo work affected by misconduct."),
        ("assessment-invalidated", "Assessment Invalidated", "academic", "Assessment invalidated according to policy."),
        ("integrity-probation", "Academic Integrity Probation", "academic", "Student placed under academic integrity monitoring."),
        ("counseling-referral", "Counseling Referral", "supportive", "Formal referral for counseling support."),
        ("mentorship-assignment", "Mentorship Assignment", "supportive", "Student assigned to staff mentor."),
        ("behavior-intervention-plan", "Behavior Intervention Plan", "supportive", "Formal intervention goals and review plan."),
        ("substance-intervention", "Substance Abuse Intervention", "supportive", "Referral to approved intervention program."),
        ("safety-assessment", "Safety Assessment", "supportive", "Threat/risk/safety assessment initiated."),
        ("in-school-suspension", "In-School Suspension", "suspension", "Student supervised in-school away from regular classes."),
        ("out-school-suspension", "Out-of-School Suspension", "suspension", "Student prohibited from attending school temporarily."),
        ("activity-suspension", "Activity Suspension", "suspension", "Student suspended from activities or extracurriculars."),
        ("transport-suspension", "Transportation Suspension", "suspension", "Student temporarily loses school transportation privileges."),
        ("alternative-class-placement", "Alternative Classroom Placement", "placement", "Temporary reassignment to another supervised classroom."),
        ("alternative-school-placement", "Alternative School Placement", "placement", "Transfer to alternative education program."),
        ("emergency-removal", "Emergency Removal", "placement", "Immediate removal due to urgent safety concern."),
        ("disciplinary-probation", "Disciplinary Probation", "severe", "Student remains enrolled under strict conditions."),
        ("recommended-transfer", "Recommended Transfer", "severe", "School recommends transfer to another program."),
        ("expulsion-recommendation", "Expulsion Recommendation", "severe", "Administration recommends expulsion to decision-maker."),
        ("expulsion", "Expulsion", "severe", "Formal removal from school for defined or permanent period."),
        ("law-enforcement-referral", "Law Enforcement Referral", "administrative", "Incident referred to law enforcement as required."),
        ("child-protection-referral", "Child Protection Referral", "administrative", "Concern referred to child protection or safeguarding authority."),
        ("no-disciplinary-action", "No Disciplinary Action", "administrative", "Investigation found no violation or insufficient evidence."),
        ("action-overturned", "Action Overturned", "administrative", "Previous disciplinary action reversed after review or appeal."),
    ]

    for code, name, category, description in defaults:
        DisciplinaryActionType.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "category": category,
                "description": description,
                "requires_start_date": True,
                "requires_end_date": False,
                "requires_parent_notification": category in {"suspension", "severe"},
                "requires_approval": category in {"suspension", "severe", "administrative"},
            },
        )


def unseed_default_action_types(apps, schema_editor):
    DisciplinaryActionType = apps.get_model("students", "DisciplinaryActionType")
    codes = [
        "verbal-warning",
        "counseling-session",
        "teacher-conference",
        "parent-notification",
        "parent-conference",
        "written-warning",
        "behavior-reflection",
        "apology-required",
        "behavior-contract",
        "restorative-conference",
        "restitution",
        "loss-of-privileges",
        "classroom-removal",
        "assigned-seating",
        "detention",
        "community-service",
        "assignment-make-up",
        "assessment-invalidated",
        "integrity-probation",
        "counseling-referral",
        "mentorship-assignment",
        "behavior-intervention-plan",
        "substance-intervention",
        "safety-assessment",
        "in-school-suspension",
        "out-school-suspension",
        "activity-suspension",
        "transport-suspension",
        "alternative-class-placement",
        "alternative-school-placement",
        "emergency-removal",
        "disciplinary-probation",
        "recommended-transfer",
        "expulsion-recommendation",
        "expulsion",
        "law-enforcement-referral",
        "child-protection-referral",
        "no-disciplinary-action",
        "action-overturned",
    ]
    DisciplinaryActionType.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0012_studentdisciplinaryaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdisciplinaryaction",
            name="duration_days",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="studentdisciplinaryaction",
            name="severity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Minor"),
                    (2, "Moderate"),
                    (3, "Serious"),
                    (4, "Severe"),
                    (5, "Critical"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="DisciplinaryActionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.SlugField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("informal", "Informal"),
                            ("corrective", "Corrective"),
                            ("restrictive", "Restrictive"),
                            ("academic", "Academic"),
                            ("supportive", "Supportive"),
                            ("suspension", "Suspension"),
                            ("placement", "Placement"),
                            ("severe", "Severe"),
                            ("administrative", "Administrative"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("requires_start_date", models.BooleanField(default=True)),
                ("requires_end_date", models.BooleanField(default=False)),
                ("requires_parent_notification", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplinary Action Type",
                "verbose_name_plural": "Disciplinary Action Types",
                "db_table": "disciplinary_action_type",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="studentdisciplinaryaction",
            name="action_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_actions",
                to="students.disciplinaryactiontype",
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryactiontype",
            index=models.Index(
                fields=["category"], name="disciplinar_categor_467c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinaryactiontype",
            index=models.Index(fields=["code"], name="disciplinar_code_fd7e5b_idx"),
        ),
        migrations.RunPython(seed_default_action_types, unseed_default_action_types),
    ]
