# Generated by Django 5.2.10 on 2026-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0013_studentdisciplinaryaction_duration_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinaryactiontype",
            name="allow_manual_override",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="disciplinaryactiontype",
            name="default_duration_days",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="disciplinaryactiontype",
            name="default_severity",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="disciplinaryactiontype",
            name="max_duration_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
