from django.db import migrations


CURATED_DEFAULTS = [
    {
        "code": "verbal-warning",
        "name": "Verbal Warning",
        "category": "informal",
        "description": "Staff member verbally corrects behavior and records the incident.",
        "default_duration_days": 1,
        "max_duration_days": 1,
        "default_severity": 1,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "written-warning",
        "name": "Written Warning",
        "category": "corrective",
        "description": "Official written warning filed for repeat or moderate misconduct.",
        "default_duration_days": 1,
        "max_duration_days": 1,
        "default_severity": 1,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "parent-guardian-notification",
        "name": "Parent/Guardian Notification",
        "category": "corrective",
        "description": "Parent or guardian is formally notified of the incident.",
        "default_duration_days": 1,
        "max_duration_days": 1,
        "default_severity": 1,
        "allow_manual_override": True,
        "requires_parent_notification": True,
        "requires_approval": False,
    },
    {
        "code": "behavior-reflection-assignment",
        "name": "Behavior Reflection Assignment",
        "category": "corrective",
        "description": "Student completes a reflection task focused on behavior and expectations.",
        "default_duration_days": 1,
        "max_duration_days": 3,
        "default_severity": 1,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "counseling-referral",
        "name": "Counseling Referral",
        "category": "supportive",
        "description": "Student is referred to counseling for support and follow-up.",
        "default_duration_days": 1,
        "max_duration_days": 5,
        "default_severity": 2,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "lunch-detention",
        "name": "Lunch Detention",
        "category": "restrictive",
        "description": "Student serves supervised detention during lunch period.",
        "default_duration_days": 1,
        "max_duration_days": 3,
        "default_severity": 2,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "after-school-detention",
        "name": "After-School Detention",
        "category": "restrictive",
        "description": "Student serves supervised detention after school.",
        "default_duration_days": 1,
        "max_duration_days": 5,
        "default_severity": 2,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "loss-of-privileges",
        "name": "Loss of Privileges",
        "category": "restrictive",
        "description": "Temporary removal of selected privileges due to misconduct.",
        "default_duration_days": 2,
        "max_duration_days": 10,
        "default_severity": 2,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "classroom-removal-temporary",
        "name": "Classroom Removal (Temporary)",
        "category": "restrictive",
        "description": "Student is removed from class temporarily for safety or order.",
        "default_duration_days": 1,
        "max_duration_days": 2,
        "default_severity": 3,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "behavior-contract",
        "name": "Behavior Contract",
        "category": "supportive",
        "description": "Student and school agree on documented behavior expectations.",
        "default_duration_days": 5,
        "max_duration_days": 20,
        "default_severity": 2,
        "allow_manual_override": True,
        "requires_parent_notification": True,
        "requires_approval": False,
    },
    {
        "code": "in-school-suspension",
        "name": "In-School Suspension",
        "category": "suspension",
        "description": "Student is suspended from regular classes while remaining on campus.",
        "default_duration_days": 2,
        "max_duration_days": 5,
        "default_severity": 3,
        "allow_manual_override": False,
        "requires_parent_notification": True,
        "requires_approval": True,
    },
    {
        "code": "out-of-school-suspension-short",
        "name": "Out-of-School Suspension (Short)",
        "category": "suspension",
        "description": "Short external suspension for serious misconduct.",
        "default_duration_days": 3,
        "max_duration_days": 5,
        "default_severity": 4,
        "allow_manual_override": False,
        "requires_parent_notification": True,
        "requires_approval": True,
    },
    {
        "code": "out-of-school-suspension-extended",
        "name": "Out-of-School Suspension (Extended)",
        "category": "suspension",
        "description": "Extended external suspension for repeated or severe misconduct.",
        "default_duration_days": 7,
        "max_duration_days": 10,
        "default_severity": 4,
        "allow_manual_override": False,
        "requires_parent_notification": True,
        "requires_approval": True,
    },
    {
        "code": "restorative-conference",
        "name": "Restorative Conference",
        "category": "corrective",
        "description": "Structured restorative meeting to repair harm and set next steps.",
        "default_duration_days": 1,
        "max_duration_days": 3,
        "default_severity": 2,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "academic-integrity-violation-record",
        "name": "Academic Integrity Violation Record",
        "category": "academic",
        "description": "Record for plagiarism, cheating, or related academic integrity incidents.",
        "default_duration_days": 1,
        "max_duration_days": 5,
        "default_severity": 3,
        "allow_manual_override": True,
        "requires_parent_notification": False,
        "requires_approval": False,
    },
    {
        "code": "disciplinary-probation",
        "name": "Probation (Disciplinary)",
        "category": "severe",
        "description": "Student remains enrolled under strict probation conditions and review.",
        "default_duration_days": 10,
        "max_duration_days": 30,
        "default_severity": 4,
        "allow_manual_override": False,
        "requires_parent_notification": True,
        "requires_approval": True,
    },
    {
        "code": "emergency-safety-removal",
        "name": "Emergency Safety Removal",
        "category": "severe",
        "description": "Immediate temporary removal from normal setting due to urgent safety concerns.",
        "default_duration_days": 1,
        "max_duration_days": 3,
        "default_severity": 5,
        "allow_manual_override": False,
        "requires_parent_notification": True,
        "requires_approval": True,
    },
    {
        "code": "enrollment-withdrawal-recommendation",
        "name": "Enrollment Withdrawal Recommendation",
        "category": "administrative",
        "description": "Formal recommendation to withdraw enrollment pending final decision.",
        "default_duration_days": 1,
        "max_duration_days": 1,
        "default_severity": 5,
        "allow_manual_override": False,
        "requires_parent_notification": True,
        "requires_approval": True,
    },
    {
        "code": "final-enrollment-withdrawal",
        "name": "Final Enrollment Withdrawal",
        "category": "administrative",
        "description": "Final administrative withdrawal of student enrollment.",
        "default_duration_days": 1,
        "max_duration_days": 1,
        "default_severity": 5,
        "allow_manual_override": False,
        "requires_parent_notification": True,
        "requires_approval": True,
    },
    {
        "code": "action-reversal-cleared-record",
        "name": "Action Reversal / Cleared Record",
        "category": "administrative",
        "description": "Administrative reversal or cleared record after review.",
        "default_duration_days": 1,
        "max_duration_days": 1,
        "default_severity": 1,
        "allow_manual_override": False,
        "requires_parent_notification": False,
        "requires_approval": True,
    },
]


LEGACY_SEED_CODES = {
    "verbal-warning",
    "counseling-session",
    "teacher-conference",
    "parent-notification",
    "parent-conference",
    "written-warning",
    "behavior-reflection",
    "apology-required",
    "behavior-contract",
    "restorative-conference",
    "restitution",
    "loss-of-privileges",
    "classroom-removal",
    "assigned-seating",
    "detention",
    "community-service",
    "assignment-make-up",
    "assessment-invalidated",
    "integrity-probation",
    "counseling-referral",
    "mentorship-assignment",
    "behavior-intervention-plan",
    "substance-intervention",
    "safety-assessment",
    "in-school-suspension",
    "out-school-suspension",
    "activity-suspension",
    "transport-suspension",
    "alternative-class-placement",
    "alternative-school-placement",
    "emergency-removal",
    "disciplinary-probation",
    "recommended-transfer",
    "expulsion-recommendation",
    "expulsion",
    "law-enforcement-referral",
    "child-protection-referral",
    "no-disciplinary-action",
    "action-overturned",
}


def apply_curated_defaults(apps, schema_editor):
    DisciplinaryActionType = apps.get_model("students", "DisciplinaryActionType")

    curated_codes = set()
    for item in CURATED_DEFAULTS:
        curated_codes.add(item["code"])

        DisciplinaryActionType.objects.update_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "category": item["category"],
                "description": item["description"],
                "requires_start_date": True,
                "requires_end_date": False,
                "requires_parent_notification": item["requires_parent_notification"],
                "requires_approval": item["requires_approval"],
                "default_duration_days": item["default_duration_days"],
                "max_duration_days": item["max_duration_days"],
                "default_severity": item["default_severity"],
                "allow_manual_override": item["allow_manual_override"],
                "active": True,
            },
        )

    # Keep historical records valid by deactivating previous seed-only options
    # instead of deleting them.
    legacy_only_codes = LEGACY_SEED_CODES - curated_codes
    DisciplinaryActionType.objects.filter(code__in=legacy_only_codes).update(active=False)


def noop_reverse(apps, schema_editor):
    # Intentionally no destructive reverse operation.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0014_disciplinaryactiontype_allow_manual_override_and_more"),
    ]

    operations = [
        migrations.RunPython(apply_curated_defaults, noop_reverse),
    ]
