# Generated by Django 5.2.17 on 2026-09-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_enrollment_year_end_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentguardian',
            name='parent_profile_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='portal_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='portal_approved_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='portal_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='portal_state',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('disconnected', 'Disconnected')], default='unverified', max_length=16),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='portal_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
