# Generated by Django 5.2.17 on 2026-09-29 06:09

from django.db import migrations, models


def preserve_verified_access(apps, schema_editor):
    if schema_editor.connection.schema_name == "public":
        return
    apps.get_model("students", "StudentGuardian").objects.filter(
        portal_state="active", portal_verified_at__isnull=False, portal_approved_at__isnull=False,
        portal_ended_at__isnull=True, parent_profile_id__isnull=False, active=True,
    ).update(give_access=True)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_studentguardian_parent_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcontact',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentcontact',
            name='portal_guardian_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='give_access',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_verified_access, migrations.RunPython.noop),
    ]
