# Generated by Django 5.2.17 on 2026-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_studentcontact_date_of_birth_studentcontact_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontact',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
