# Generated by Django 5.2.11 on 2026-03-05 05:02

import core.models
import core.validators
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "db_table": "domain",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True, verbose_name="Tenant URL Name")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        default=core.models.generate_unique_id_number,
                        help_text="Unique identifier for the tenant",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "funding_type",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("public", "Public"),
                            ("charter", "Charter"),
                            ("international", "International"),
                            ("online", "Online"),
                        ],
                        default="private",
                        help_text="Funding type: private, public, charter, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("higher_education", "Higher_education"),
                            ("vocational", "Vocational"),
                            ("k12", "K12"),
                        ],
                        default="primary",
                        help_text="School type: primary, secondary, tertiary, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        help_text="School motto/slogan",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "emis_number",
                    models.CharField(
                        blank=True,
                        help_text="Education Management Information System number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the tenant",
                        null=True,
                    ),
                ),
                (
                    "date_est",
                    models.DateField(
                        blank=True, help_text="Date established", null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Street address",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("closed", "Closed"),
                            ("inactive", "Inactive"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        help_text="Tenant status: active, on_hold, closed, inactive, deleted",
                        max_length=20,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Quick boolean flag for active status (status='active' = active=True)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Tenant logo stored in tenant-specific folder: tenants/{schema_name}/logo/",
                        null=True,
                        upload_to=core.models.tenant_logo_upload_path,
                        validators=[core.validators.ValidateImageFile],
                    ),
                ),
                (
                    "logo_shape",
                    models.CharField(
                        choices=[("square", "Square"), ("landscape", "Landscape")],
                        default="square",
                        help_text="Shape of the logo: Square (1:1) or Landscape (2:1 width:height)",
                        max_length=100,
                    ),
                ),
                (
                    "theme_color",
                    models.CharField(
                        blank=True,
                        help_text="Brand/theme color (hex code)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "theme_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Comprehensive theme configuration including colors, typography, spacing, shadows, etc.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenant",
                "ordering": ["name"],
            },
        ),
    ]
