# Generated by Django 5.2.10 on 2026-05-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_tenant_disabled_access_overrides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Controls whether the workspace is operational. This is independent of lifecycle status.",
            ),
        ),
    ]
