# Generated by Django 5.2.10 on 2026-05-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_tenant_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("school_name", models.CharField(max_length=255)),
                ("role_title", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("students_count", models.CharField(max_length=50)),
                ("workspace_slug", models.CharField(blank=True, max_length=30)),
                ("plan", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("onboarded", "Onboarded"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Signup Request",
                "verbose_name_plural": "Signup Requests",
                "db_table": "signup_request",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
