# Generated by Django 5.2.10 on 2026-07-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_platform_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the onboarding wizard was completed and workspace provisioned.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="onboarding_plan",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Onboarding configuration plan. Stores per-step payloads, status, and the final apply result. Structure: {version, current_step, steps, required_steps, optional_steps, started_at, completed_at, apply_result}.",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="onboarding_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user first started the onboarding wizard.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("closed", "Closed"),
                    ("inactive", "Inactive"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                help_text="Tenant lifecycle status. pending/in_progress are onboarding states; active/on_hold/etc are operational states.",
                max_length=20,
            ),
        ),
    ]
