# Generated by Django 5.2.10 on 2026-08-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tenant_creation_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='school_type',
        ),
        migrations.AddField(
            model_name='tenant',
            name='school_division_id',
            field=models.UUIDField(blank=True, help_text="ID of the configured Division in this tenant's schema.", null=True),
        ),
    ]
