# Generated by Django 5.2.17 on 2026-08-25 19:00

from django.db import migrations, models


def mark_existing_jobs_as_clones(apps, schema_editor):
    """Every job that predates this field was clone-only."""
    TenantCreationJob = apps.get_model('core', 'TenantCreationJob')
    TenantCreationJob.objects.exclude(source_schema='').update(initialization_source='clone')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sync_onboarding_school_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcreationjob',
            name='initialization_source',
            field=models.CharField(choices=[('default', 'Default setup'), ('clone', 'Cloned from source tenant')], default='default', max_length=20),
        ),
        migrations.RunPython(mark_existing_jobs_as_clones, migrations.RunPython.noop),
    ]
