# Generated by Django 5.2.17 on 2026-08-26 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tenant_creation_job_initialization_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('SYSTEM', 'System'), ('CUSTOM', 'Custom')], max_length=10)),
                ('scope', models.CharField(choices=[('PUBLIC', 'Public workspace'), ('TENANT', 'Tenant workspace'), ('GLOBAL', 'Public and tenant workspaces')], max_length=10)),
                ('system_key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('permissions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('permission_version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shared_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_shared_role',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('role_type', 'SYSTEM'), ('system_key__isnull', False)), models.Q(('role_type', 'CUSTOM'), ('system_key__isnull', True)), _connector='OR'), name='core_shared_role_type_key_consistent')],
            },
        ),
    ]
