# Generated by Django 5.2.17 on 2026-08-26 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_shared_role_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='core.sharedrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_role_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_shared_role_assignment',
            },
        ),
    ]
