# Generated by Django 5.2.17 on 2026-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_tenant_restoration_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuthAppearance',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_layout', models.CharField(default='classic', max_length=16)),
                ('workspace_layout', models.CharField(blank=True, default='', max_length=16)),
                ('parent_layout', models.CharField(blank=True, default='', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
