# Generated by Django 5.2.11 on 2026-05-02 00:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=20, unique=True)),
                ("bank_number", models.CharField(blank=True, max_length=20, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "bank_account",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("code", models.CharField(max_length=3)),
            ],
            options={
                "db_table": "currency",
            },
        ),
        migrations.CreateModel(
            name="GeneralFeeList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
                ),
                (
                    "student_target",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "general_fee_list",
            },
        ),
        migrations.CreateModel(
            name="PaymentInstallment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the installment. Auto-generated as 'Installment {sequence}' if not provided.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Individual percentage (0-100) for this installment. Total of all installments should equal 100%",
                        max_digits=10,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(help_text="Due date for this installment"),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Order/sequence of this installment (1, 2, 3, ...). Auto-generated if not provided.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Installment",
                "verbose_name_plural": "Payment Installments",
                "db_table": "payment_installment",
                "ordering": ["academic_year", "sequence", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("is_editable", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payment_method",
            },
        ),
        migrations.CreateModel(
            name="SectionFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            options={
                "db_table": "section_fee",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("type_code", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("expense", "Expense"), ("income", "Income")],
                        max_length=8,
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_editable", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "transaction_type",
                "ordering": ["name"],
            },
        ),
    ]
