# Generated by Django 5.2.10 on 2026-05-27 22:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0005_accountingcashtransaction_student"),
        ("hr", "0009_alter_employee_basic_salary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCompensation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                        ],
                        default="salary",
                        max_length=20,
                    ),
                ),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("effective_start_date", models.DateField()),
                ("effective_end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_v2_compensations",
                        to="accounting.accountingcurrency",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_v2_compensations",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_compensation",
                "ordering": ["-effective_start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollCatalogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("deduction", "Deduction"),
                            ("tax", "Tax"),
                            ("benefit", "Benefit"),
                            ("reimbursement", "Reimbursement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=False)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_item",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePayrollItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_override", models.CharField(blank=True, max_length=120)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="flat",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                ("formula", models.TextField(blank=True)),
                (
                    "target_amount_source",
                    models.CharField(
                        choices=[
                            ("basic_salary", "Basic Salary"),
                            ("gross_pay", "Gross Pay"),
                            ("taxable_income", "Taxable Income"),
                            ("annual_salary", "Annual Salary"),
                        ],
                        default="gross_pay",
                        max_length=50,
                    ),
                ),
                (
                    "calculation_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("is_taxable", models.BooleanField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("semimonthly", "Semi-Monthly"),
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                        ],
                        default="one_time",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_v2_items",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="payroll_v2.payrollcatalogitem",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_employee_item",
                "ordering": [
                    "priority",
                    "payroll_item__priority",
                    "payroll_item__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollCatalogItemRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="flat",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                ("formula", models.TextField(blank=True)),
                (
                    "target_amount_source",
                    models.CharField(
                        choices=[
                            ("basic_salary", "Basic Salary"),
                            ("gross_pay", "Gross Pay"),
                            ("taxable_income", "Taxable Income"),
                            ("annual_salary", "Annual Salary"),
                        ],
                        default="gross_pay",
                        max_length=50,
                    ),
                ),
                (
                    "target_min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "target_max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "calculation_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("effective_start_date", models.DateField(blank=True, null=True)),
                ("effective_end_date", models.DateField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="payroll_v2.payrollcatalogitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_item_rule",
                "ordering": [
                    "payroll_item__priority",
                    "priority",
                    "target_min_amount",
                    "name",
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollEmployeeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "gross_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "taxable_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_benefits",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_reimbursements",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="unpaid",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "compensation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_payroll_items",
                        to="payroll_v2.employeecompensation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_v2_employee_items",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_employee_run_item",
                "ordering": ["employee__first_name", "employee__last_name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("deduction", "Deduction"),
                            ("tax", "Tax"),
                            ("benefit", "Benefit"),
                            ("reimbursement", "Reimbursement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="flat",
                        max_length=30,
                    ),
                ),
                (
                    "target_amount_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic_salary", "Basic Salary"),
                            ("gross_pay", "Gross Pay"),
                            ("taxable_income", "Taxable Income"),
                            ("annual_salary", "Annual Salary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("one_time", "One Time"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("semimonthly", "Semi-Monthly"),
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_type", models.CharField(blank=True, max_length=80)),
                ("source_id", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_payroll_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_line_items",
                        to="payroll_v2.employeepayrollitem",
                    ),
                ),
                (
                    "payroll_employee_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="payroll_v2.payrollemployeeitem",
                    ),
                ),
                (
                    "payroll_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_line_items",
                        to="payroll_v2.payrollcatalogitem",
                    ),
                ),
                (
                    "payroll_item_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_line_items",
                        to="payroll_v2.payrollcatalogitemrule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_line_item",
                "ordering": ["line_type", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPayslipTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("layout", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_payslip_template",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRunRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payroll_number", models.CharField(max_length=50)),
                (
                    "payroll_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("bonus", "Bonus"),
                            ("commission", "Commission"),
                            ("overtime", "Overtime"),
                            ("adjustment", "Adjustment"),
                            ("termination", "Termination"),
                        ],
                        default="regular",
                        max_length=30,
                    ),
                ),
                ("pay_period_start", models.DateField()),
                ("pay_period_end", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("table_view_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "payslip_template_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "gross_pay_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "deduction_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "benefit_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "reimbursement_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "net_pay_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_v2_runs_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_v2_runs",
                        to="accounting.accountingbankaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_v2_runs",
                        to="accounting.accountingcurrency",
                    ),
                ),
                (
                    "payslip_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_runs",
                        to="payroll_v2.payrollpaysliptemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_run",
                "ordering": ["-pay_period_end", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payrollemployeeitem",
            name="payroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_items",
                to="payroll_v2.payrollrunrecord",
            ),
        ),
        migrations.CreateModel(
            name="PayrollTableView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "applies_to",
                    models.CharField(blank=True, default="payroll_run", max_length=50),
                ),
                ("columns", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("sorting", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_table_view",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="payrollrunrecord",
            name="table_view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_runs",
                to="payroll_v2.payrolltableview",
            ),
        ),
        migrations.AddIndex(
            model_name="employeecompensation",
            index=models.Index(
                fields=["employee", "is_active"], name="payroll_v2__employe_987673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeecompensation",
            index=models.Index(
                fields=["effective_start_date", "effective_end_date"],
                name="payroll_v2__effecti_9c9aa6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcatalogitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("code",),
                name="payroll_v2_uniq_item_code_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="employeepayrollitem",
            index=models.Index(
                fields=["employee", "is_active"], name="payroll_v2__employe_34593b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeepayrollitem",
            index=models.Index(
                fields=["start_date", "end_date"], name="payroll_v2__start_d_3610dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollcatalogitemrule",
            index=models.Index(
                fields=["payroll_item", "is_active"],
                name="payroll_v2__payroll_7e3f01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollcatalogitemrule",
            index=models.Index(
                fields=[
                    "target_amount_source",
                    "target_min_amount",
                    "target_max_amount",
                ],
                name="payroll_v2__target__390621_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrolllineitem",
            index=models.Index(
                fields=["payroll_employee_item", "line_type"],
                name="payroll_v2__payroll_443064_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrolllineitem",
            index=models.Index(
                fields=["payroll_item", "name"], name="payroll_v2__payroll_eb2cbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpaysliptemplate",
            index=models.Index(
                fields=["is_default"], name="payroll_v2__is_defa_f1c05d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollemployeeitem",
            index=models.Index(
                fields=["payroll", "employee"], name="payroll_v2__payroll_fd0456_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollemployeeitem",
            index=models.Index(
                fields=["payment_status"], name="payroll_v2__payment_cc5fbf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollemployeeitem",
            constraint=models.UniqueConstraint(
                fields=("payroll", "employee"), name="payroll_v2_uniq_run_employee"
            ),
        ),
        migrations.AddIndex(
            model_name="payrolltableview",
            index=models.Index(
                fields=["is_default", "applies_to"],
                name="payroll_v2__is_defa_dac47b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrunrecord",
            index=models.Index(fields=["status"], name="payroll_v2__status_30af82_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollrunrecord",
            index=models.Index(
                fields=["pay_period_start", "pay_period_end"],
                name="payroll_v2__pay_per_07326b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrunrecord",
            constraint=models.UniqueConstraint(
                fields=("payroll_number",), name="payroll_v2_uniq_run_number"
            ),
        ),
    ]
