# Generated by Django 5.2.10 on 2026-06-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_v2", "0013_payroll_settings_schema_repair"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollrunrecord",
            name="paid_table_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
