# Generated by Django 5.2.11 on 2026-08-09 17:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0009_alter_academicyear_options_and_more"),
        ("hr", "0012_remove_employee_tax_rules"),
        ("payroll_v2", "0014_payrollrunrecord_paid_table_snapshot"),
        ("students", "0017_discipline_attendance_effects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("child", "Child"),
                            ("dependent", "Dependent"),
                            ("legal_guardian", "Legal Guardian"),
                            ("other", "Other"),
                        ],
                        default="child",
                        max_length=30,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="hr.employee",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_sponsors",
                        to="students.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_employee_wards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_employee_ward",
                "ordering": [
                    "employee__last_name",
                    "employee__first_name",
                    "student__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollDeductionSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("staff_ward_sponsorship", "Staff Ward Sponsorship"),
                            ("salary_advance", "Salary Advance"),
                            ("loan", "Loan"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_id", models.CharField(max_length=80)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "scheduled_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("partially_applied", "Partially Applied"),
                            ("applied", "Applied"),
                            ("deferred", "Deferred"),
                            ("adjusted", "Adjusted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deduction_schedules",
                        to="hr.employee",
                    ),
                ),
                (
                    "end_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deduction_schedules_ending",
                        to="payroll_v2.payrollperiod",
                    ),
                ),
                (
                    "start_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deduction_schedules_starting",
                        to="payroll_v2.payrollperiod",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_deduction_schedule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollDeductionInstallment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("applied", "Applied"),
                            ("adjusted", "Adjusted"),
                            ("deferred", "Deferred"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=30,
                    ),
                ),
                ("adjustment_reason", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deduction_installments",
                        to="payroll_v2.payrolllineitem",
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deduction_installments",
                        to="payroll_v2.payrollperiod",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deduction_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="payroll_v2.payrolldeductionschedule",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_deduction_installment",
                "ordering": ["payroll_period__start_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "repayment_method",
                    models.CharField(
                        choices=[
                            ("fixed_installment", "Fixed Installment"),
                            ("equal_split", "Equal Split"),
                        ],
                        default="equal_split",
                        max_length=30,
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("number_of_installments", models.PositiveSmallIntegerField(default=1)),
                (
                    "remaining_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_salary_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_advances",
                        to="hr.employee",
                    ),
                ),
                (
                    "repayment_start_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_advances_starting",
                        to="payroll_v2.payrollperiod",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_salary_advance",
                "ordering": ["-request_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffWardSponsorshipPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("maximum_wards", models.PositiveSmallIntegerField(default=1)),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "coverage_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "employee_contribution_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "employee_contribution_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "max_payroll_deduction_percent_of_gross",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                (
                    "min_net_pay_percent_of_gross",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                (
                    "max_total_voluntary_deduction_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("allow_auto_adjust", models.BooleanField(default=True)),
                ("allow_deduction_deferral", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("eligible_fee_types", models.JSONField(blank=True, default=list)),
                (
                    "eligible_employment_types",
                    models.JSONField(blank=True, default=list),
                ),
                ("minimum_service_months", models.PositiveSmallIntegerField(default=0)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_staff_ward_sponsorship_policy",
                "ordering": ["-effective_from", "name"],
            },
        ),
        migrations.CreateModel(
            name="StaffWardSponsorship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_sponsored_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "school_contribution_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "employee_contribution_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "payroll_recovery_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_ward_sponsorships",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_staff_ward_sponsorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ward_sponsorships",
                        to="hr.employee",
                    ),
                ),
                (
                    "end_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ending_sponsorships",
                        to="payroll_v2.payrollperiod",
                    ),
                ),
                (
                    "start_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="starting_sponsorships",
                        to="payroll_v2.payrollperiod",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sponsorships",
                        to="payroll_v2.staffwardsponsorshippolicy",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_staff_ward_sponsorship",
                "ordering": ["-application_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffWardSponsorshipStudent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eligible_fee_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "school_covered_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "employee_responsibility_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sponsorship_rows",
                        to="payroll_v2.employeeward",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_sponsorship_rows",
                        to="students.enrollment",
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorship_students",
                        to="payroll_v2.staffwardsponsorship",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sponsorship_rows",
                        to="students.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_v2_staff_ward_sponsorship_student",
                "ordering": ["student__last_name", "student__first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="employeeward",
            index=models.Index(
                fields=["employee", "is_active"], name="payroll_v2__employe_442488_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeward",
            index=models.Index(
                fields=["student", "is_active"], name="payroll_v2__student_fb101d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeward",
            constraint=models.UniqueConstraint(
                fields=("employee", "student"),
                name="payroll_v2_uniq_employee_student_ward",
            ),
        ),
        migrations.AddIndex(
            model_name="payrolldeductionschedule",
            index=models.Index(
                fields=["employee", "status"], name="payroll_v2__employe_1c42e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrolldeductionschedule",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="payroll_v2__source__2fc86b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrolldeductioninstallment",
            constraint=models.UniqueConstraint(
                fields=("deduction_schedule", "payroll_period"),
                name="payroll_v2_uniq_schedule_installment_period",
            ),
        ),
        migrations.AddIndex(
            model_name="salaryadvance",
            index=models.Index(
                fields=["employee", "status"], name="payroll_v2__employe_336aa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryadvance",
            index=models.Index(
                fields=["status", "request_date"], name="payroll_v2__status_03a0c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffwardsponsorshippolicy",
            index=models.Index(
                fields=["is_active", "effective_from", "effective_to"],
                name="payroll_v2__is_acti_a8ce45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffwardsponsorship",
            index=models.Index(
                fields=["employee", "status"], name="payroll_v2__employe_0b05f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffwardsponsorship",
            index=models.Index(
                fields=["academic_year", "status"],
                name="payroll_v2__academi_8bdbcb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffwardsponsorshipstudent",
            constraint=models.UniqueConstraint(
                fields=("sponsorship", "enrollment"),
                name="payroll_v2_uniq_sponsorship_enrollment",
            ),
        ),
    ]
