# Generated by Django 5.2.11 on 2026-08-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_v2", "0015_employeeward_payrolldeductionschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsettings",
            name="salary_advance_default_installments",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Default number of installments suggested for a salary advance.",
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="salary_advance_default_repayment_method",
            field=models.CharField(
                choices=[
                    ("fixed_installment", "Fixed Installment"),
                    ("equal_split", "Equal Split"),
                ],
                default="equal_split",
                help_text="Default repayment method used when creating a salary advance request.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="salary_advance_max_installments",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Maximum number of installments allowed for a salary advance.",
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="salary_advance_min_service_months",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minimum service months required before an employee can request a salary advance.",
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="salary_advance_requires_approval",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, salary advance requests must be approved before they can be activated.",
            ),
        ),
    ]
