# Generated by Django 5.2.11 on 2026-03-05 05:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("level", models.PositiveIntegerField(default=1)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("intern", "Intern"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "compensation_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("hourly", "Hourly"),
                            ("stipend", "Stipend"),
                        ],
                        default="salary",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("teaching_role", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "position",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="PositionCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "position_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150)),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default=None, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("on_leave", "On Leave"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="staff"
                    ),
                ),
                ("id_number", models.CharField(max_length=20, unique=True)),
                (
                    "is_teacher",
                    models.BooleanField(
                        default=False,
                        help_text="Direct flag to mark staff as teacher, independent of position",
                    ),
                ),
                (
                    "user_account_id_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="User ID number (string reference to User.id_number in public schema). Loose coupling instead of cross-schema FK.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("suspension_date", models.DateField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "staff",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teacher_schedule",
            },
        ),
        migrations.CreateModel(
            name="TeacherSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teacher_section",
            },
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teacher_subject",
            },
        ),
    ]
