# Generated by Django 5.2.11 on 2026-04-17 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "academics",
            "0011_rename_school_cale_event_t_2908fb_idx_calendar_ev_event_t_3e18c8_idx_and_more",
        ),
        ("staff", "0004_remove_duplicate_teacher_subjects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teachersubject",
            constraint=models.UniqueConstraint(
                fields=("teacher", "section_subject"),
                name="unique_teacher_section_subject",
            ),
        ),
    ]
