from django.db.models.signals import post_delete, post_save, pre_save
from django.dispatch import receiver
import logging

from common.images import delete_old_file, set_default_image
from core.models import Tenant
from academics.services import (
    purge_schedule_projections_for_class_schedule,
    sync_schedule_projections_for_class_schedule,
)

logger = logging.getLogger(__name__)

# Simple upload function for tenant logo
def tenant_logo_upload(instance, filename):
    """Generate upload path for tenant logo"""
    return f"logo/{filename}"

# Signal to handle default logo upload and replacement
@receiver(post_save, sender=Tenant)
def upload_default_logo(sender, instance, created, **kwargs):
    set_default_image(
        instance,
        created,
        tenant_logo_upload,
        field_name="logo",
        default_img_path="images/logo.png",
        id_field="id_number",
        extension="png",
    )


@receiver(pre_save, sender=Tenant)
def replace_logo(sender, instance, **kwargs):
    delete_old_file(
        instance,
        Tenant,
        field_name="logo",
    )
    # if not instance.pk:
    #     return  # Skip if the instance is being created
    # try:
    #     old_instance = Tenant.objects.get(pk=instance.pk)
    #     if old_instance.logo and old_instance.logo != instance.logo:
    #         # Delete the old logo file
    #         if os.path.isfile(old_instance.logo.path):
    #             os.remove(old_instance.logo.path)
    # except School.DoesNotExist:
    #     pass


@receiver(post_save, sender=Tenant)
def setup_tenant_defaults(sender, instance, created, **kwargs):
    """
    Signal: on tenant creation, generate the onboarding plan template.

    NOTE: Default data (academic records, finance, etc.) is no longer
    auto-applied here. It is provisioned later when the school admin
    completes the onboarding wizard and clicks "Create Workspace"
    (POST /api/v1/tenants/{schema}/onboarding/apply/).

    This handler still generates the initial plan if the serializer
    somehow didn't do it (e.g. direct ORM creation in tests/scripts).
    """
    if not created:
        return
    if instance.schema_name == 'public':
        logger.info("Skipping onboarding plan for public tenant")
        return

    if instance.onboarding_plan:
        # Already generated by CreateTenantSerializer — nothing to do
        return

    try:
        from defaults.services import build_initial_plan
        instance.onboarding_plan = build_initial_plan(instance)
        instance.save(update_fields=["onboarding_plan"])
        logger.info(f"Generated onboarding plan for tenant: {instance.name}")
    except Exception as e:
        logger.error(
            f"Failed to generate onboarding plan for tenant {instance.name}: {e}",
            exc_info=True,
        )


# DISABLED: Gradebook creation now happens in bulk_create_section_subjects (supporting_adapter.py)
# This ensures atomic transaction - if gradebook creation fails, SectionSubject creation is rolled back
# Signal approach was problematic because:
# 1. Transaction boundaries unclear - SectionSubject could be saved even if gradebook fails
# 2. Harder to debug - signal runs in separate context
# 3. No transaction rollback - leads to inconsistent state
#
# @receiver(post_save, sender='academics.SectionSubject')
# def auto_create_gradebook_for_section_subject(sender, instance, created, **kwargs):
#     """[DISABLED] Gradebook creation moved to view for atomic transaction handling"""
#     pass


@receiver(post_save, sender="academics.SectionSchedule")
def sync_schedule_projections_on_schedule_save(sender, instance, **kwargs):
    sync_schedule_projections_for_class_schedule(instance)


@receiver(post_delete, sender="academics.SectionSchedule")
def purge_schedule_projections_on_schedule_delete(sender, instance, **kwargs):
    purge_schedule_projections_for_class_schedule(str(instance.id))


@receiver(post_save, sender="staff.TeacherSubject")
@receiver(post_delete, sender="staff.TeacherSubject")
def sync_schedule_projections_on_teacher_assignment_change(sender, instance, **kwargs):
    section_subject_id = getattr(instance, "section_subject_id", None)
    if not section_subject_id:
        return

    from academics.models import SectionSchedule

    schedules = SectionSchedule.objects.filter(subject_id=section_subject_id, active=True)
    for schedule in schedules:
        sync_schedule_projections_for_class_schedule(schedule)


@receiver(post_save, sender="hr.EmployeeTeacherSubject")
@receiver(post_delete, sender="hr.EmployeeTeacherSubject")
def sync_schedule_projections_on_employee_teacher_assignment_change(sender, instance, **kwargs):
    section_subject_id = getattr(instance, "section_subject_id", None)
    if not section_subject_id:
        return

    from academics.models import SectionSchedule

    schedules = SectionSchedule.objects.filter(subject_id=section_subject_id, active=True)
    for schedule in schedules:
        sync_schedule_projections_for_class_schedule(schedule)


@receiver(post_save, sender="students.Enrollment")
@receiver(post_delete, sender="students.Enrollment")
def sync_schedule_projections_on_enrollment_change(sender, instance, **kwargs):
    section_id = getattr(instance, "section_id", None)
    if not section_id:
        return

    from academics.models import SectionSchedule

    schedules = SectionSchedule.objects.filter(section_id=section_id, active=True)
    for schedule in schedules:
        sync_schedule_projections_for_class_schedule(schedule)
