# Generated by Django 5.2.11 on 2026-05-02 00:57

import core.validators
import django.utils.timezone
import django_resized.forms
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="National / government-issued identification number. Per-tenant uniqueness is enforced by subclasses where required.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default=None, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reset", "Reset"),
                            ("created", "Created"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=1,
                        size=[300, 300],
                        upload_to="photos",
                        validators=[core.validators.ValidateImageFile],
                    ),
                ),
                ("employee_number", models.CharField(max_length=30, unique=True)),
                ("hire_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "termination_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "termination_reason",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("on_leave", "On Leave"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("intern", "Intern"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "user_account_id_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Loose link to a User.id_number in the public schema.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_teacher", models.BooleanField(default=False)),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Salary"),
                            ("hourly", "Hourly Wage"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly base for MONTHLY salary types; ignored for HOURLY.",
                        max_digits=14,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Hourly rate; required for HOURLY and used for overtime computation.",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
            ],
            options={
                "db_table": "employee",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("remote", "Remote"),
                            ("on_leave", "On Leave"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                ("notes", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "employee_attendance",
                "ordering": [
                    "-attendance_date",
                    "employee__first_name",
                    "employee__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_type",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "employee_contact",
                "ordering": ["-is_primary", "first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "employee_department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDependent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="National / government-issued identification number. Per-tenant uniqueness is enforced by subclasses where required.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                ("last_name", models.CharField(max_length=150)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default=None, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reset", "Reset"),
                            ("created", "Created"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=85,
                        scale=1,
                        size=[300, 300],
                        upload_to="photos",
                        validators=[core.validators.ValidateImageFile],
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "employee_dependent",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePerformanceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review_title", models.CharField(max_length=180)),
                (
                    "review_period",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "review_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "next_review_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("needs_improvement", "Needs Improvement"),
                            ("meets_expectations", "Meets Expectations"),
                            ("exceeds_expectations", "Exceeds Expectations"),
                            ("outstanding", "Outstanding"),
                        ],
                        default="meets_expectations",
                        max_length=30,
                    ),
                ),
                (
                    "goals_summary",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("strengths", models.TextField(blank=True, default=None, null=True)),
                (
                    "improvement_areas",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "manager_comments",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "employee_comments",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=4,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "employee_performance_review",
                "ordering": [
                    "-review_date",
                    "employee__first_name",
                    "employee__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeePosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("intern", "Intern"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("can_teach", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "employee_position",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("review_note", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "leave_request",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("default_days", models.PositiveIntegerField(default=1)),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "accrual_frequency",
                    models.CharField(
                        choices=[
                            ("upfront", "Upfront"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        default="upfront",
                        max_length=20,
                    ),
                ),
                ("allow_carryover", models.BooleanField(default=False)),
                ("max_carryover_days", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "leave_type",
                "ordering": ["name"],
            },
        ),
    ]
