# Generated by Django 5.2.11 on 2026-05-02 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.utils import ProgrammingError


def _is_already_exists_error(exc):
    message = str(exc).lower()
    return "already exists" in message or "duplicate" in message


class SafeAddField(migrations.AddField):
    """AddField that tolerates pre-existing DB columns/relations."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        connection = schema_editor.connection
        sid = connection.savepoint()
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
            connection.savepoint_commit(sid)
        except ProgrammingError as exc:
            connection.savepoint_rollback(sid)
            if _is_already_exists_error(exc):
                pass
            else:
                raise

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        connection = schema_editor.connection
        sid = connection.savepoint()
        try:
            super().database_backwards(app_label, schema_editor, from_state, to_state)
            connection.savepoint_commit(sid)
        except ProgrammingError:
            connection.savepoint_rollback(sid)


class SafeAddConstraint(migrations.AddConstraint):
    """AddConstraint that tolerates pre-existing DB constraints/index relations."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        connection = schema_editor.connection
        sid = connection.savepoint()
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
            connection.savepoint_commit(sid)
        except ProgrammingError as exc:
            connection.savepoint_rollback(sid)
            if _is_already_exists_error(exc):
                pass
            else:
                raise

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        connection = schema_editor.connection
        sid = connection.savepoint()
        try:
            super().database_backwards(app_label, schema_editor, from_state, to_state)
            connection.savepoint_commit(sid)
        except ProgrammingError:
            connection.savepoint_rollback(sid)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        ("payroll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        SafeAddField(
            model_name="employee",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="hr.employee",
            ),
        ),
        SafeAddField(
            model_name="employee",
            name="pay_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="payroll.payschedule",
            ),
        ),
        SafeAddField(
            model_name="employee",
            name="tax_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Override tax rules for this employee. If empty, all active rules apply.",
                related_name="employees",
                to="payroll.taxrule",
            ),
        ),
        SafeAddField(
            model_name="employee",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeeattendance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeeattendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="hr.employee",
            ),
        ),
        SafeAddField(
            model_name="employeeattendance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeecontact",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeecontact",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="hr.employee",
            ),
        ),
        SafeAddField(
            model_name="employeecontact",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeedepartment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeedepartment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.employeedepartment",
            ),
        ),
        SafeAddField(
            model_name="employeedependent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeedependent",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependents",
                to="hr.employee",
            ),
        ),
        SafeAddField(
            model_name="employeedependent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeeperformancereview",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeeperformancereview",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_reviews",
                to="hr.employee",
            ),
        ),
        SafeAddField(
            model_name="employeeperformancereview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_conducted",
                to="hr.employee",
            ),
        ),
        SafeAddField(
            model_name="employeeperformancereview",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeeposition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employeeposition",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="hr.employeedepartment",
            ),
        ),
        SafeAddField(
            model_name="employeeposition",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.employeeposition",
            ),
        ),
        SafeAddField(
            model_name="leaverequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="hr.employee",
            ),
        ),
        SafeAddField(
            model_name="leaverequest",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="leavetype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="leavetype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        SafeAddField(
            model_name="leaverequest",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_requests",
                to="hr.leavetype",
            ),
        ),
        SafeAddConstraint(
            model_name="employeeattendance",
            constraint=models.UniqueConstraint(
                fields=("employee", "attendance_date"),
                name="hr_uniq_employee_attendance_per_day",
            ),
        ),
        SafeAddConstraint(
            model_name="employeedepartment",
            constraint=models.UniqueConstraint(
                fields=("name",), name="hr_uniq_employee_department_name_per_tenant"
            ),
        ),
        SafeAddConstraint(
            model_name="employeedepartment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("code",),
                name="hr_uniq_employee_department_code_per_tenant",
            ),
        ),
        SafeAddConstraint(
            model_name="employeeposition",
            constraint=models.UniqueConstraint(
                fields=("title", "department"),
                name="hr_uniq_employee_position_title_per_department",
            ),
        ),
        SafeAddConstraint(
            model_name="employeeposition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("code",),
                name="hr_uniq_employee_position_code_per_tenant",
            ),
        ),
        SafeAddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee_number", ""), _negated=True),
                fields=("employee_number",),
                name="hr_uniq_employee_number_per_tenant",
            ),
        ),
        SafeAddConstraint(
            model_name="leavetype",
            constraint=models.UniqueConstraint(
                fields=("name",), name="hr_uniq_leave_type_name_per_tenant"
            ),
        ),
        SafeAddConstraint(
            model_name="leavetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("code",),
                name="hr_uniq_leave_type_code_per_tenant",
            ),
        ),
    ]
