# Generated by Django 5.2.10 on 2026-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="highest_qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("primary", "Primary School"),
                    ("junior_high", "Junior High School"),
                    ("high_school", "High School / Secondary"),
                    ("vocational", "Vocational / Technical Certificate"),
                    ("associate", "Associate Degree"),
                    ("bachelor", "Bachelor's Degree"),
                    ("postgraduate_diploma", "Postgraduate Diploma"),
                    ("master", "Master's Degree"),
                    ("doctorate", "Doctorate (PhD)"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
