# Generated by Django 5.2.11 on 2026-04-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_leavetype_leaverequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="accrual_frequency",
            field=models.CharField(
                choices=[
                    ("upfront", "Upfront"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("annually", "Annually"),
                ],
                default="upfront",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="allow_carryover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="max_carryover_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
