# Generated by Django 5.2.11 on 2026-04-16 21:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_employeecompensation_payrollcomponent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("remote", "Remote"),
                            ("on_leave", "On Leave"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_attendance",
                "ordering": [
                    "-attendance_date",
                    "employee__first_name",
                    "employee__last_name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "attendance_date"),
                        name="hr_uniq_employee_attendance_per_day",
                    )
                ],
            },
        ),
    ]
