# Generated by Django 5.2.11 on 2026-04-16 22:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_employeedocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePerformanceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review_title", models.CharField(max_length=180)),
                (
                    "review_period",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "review_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "next_review_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("needs_improvement", "Needs Improvement"),
                            ("meets_expectations", "Meets Expectations"),
                            ("exceeds_expectations", "Exceeds Expectations"),
                            ("outstanding", "Outstanding"),
                        ],
                        default="meets_expectations",
                        max_length=30,
                    ),
                ),
                (
                    "goals_summary",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("strengths", models.TextField(blank=True, default=None, null=True)),
                (
                    "improvement_areas",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "manager_comments",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "employee_comments",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="hr.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_conducted",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_performance_review",
                "ordering": [
                    "-review_date",
                    "employee__first_name",
                    "employee__last_name",
                ],
            },
        ),
    ]
