# Generated by Django 5.2.10 on 2026-05-26 22:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0008_employee_annual_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="basic_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Per-period base for MONTHLY salary types; ignored for HOURLY.",
                max_digits=14,
            ),
        ),
    ]
