# Generated by Django 5.2.11 on 2026-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0009_employeeworkflowtask"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrollrun",
            options={
                "ordering": ["-run_date", "name"],
                "verbose_name": "Payroll Run",
                "verbose_name_plural": "Payroll Runs",
            },
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="payment_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="period_end",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="period_start",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
