# Generated by Django 5.2.11 on 2026-04-17 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0010_alter_payrollrun_options_payrollrun_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employee",
            name="hr_uniq_employee_number_per_tenant",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="employee_number",
            new_name="id_number",
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id_number", ""), _negated=True),
                fields=("id_number",),
                name="hr_uniq_id_number_per_tenant",
            ),
        ),
    ]
