# Generated by Django 5.2.11 on 2026-04-18 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0011_rename_employee_number_to_id_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employee",
            name="hr_uniq_id_number_per_tenant",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="id_number",
            new_name="employee_number",
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee_number", ""), _negated=True),
                fields=("employee_number",),
                name="hr_uniq_employee_number_per_tenant",
            ),
        ),
    ]
