# Generated by Django 5.2.17 on 2026-09-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantaccesstoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantaccesstoken',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
