# Generated by Django 5.2.17 on 2026-09-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_applicantaccesstoken_last_used_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='scan_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='scan_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='scan_engine',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='scan_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='scan_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='threat_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
