# Generated by Django 5.2.11 on 2026-05-02 00:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GradingSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grading_style",
                    models.CharField(
                        choices=[
                            ("single_entry", "Single Entry (Final Grades Only)"),
                            (
                                "multiple_entry",
                                "Multiple Entry (Assessments & Final Grades)",
                            ),
                        ],
                        default="multiple_entry",
                        help_text="How grades are captured: single final grade or multiple assessments",
                        max_length=20,
                    ),
                ),
                (
                    "single_entry_assessment_name",
                    models.CharField(
                        default="Final Grade",
                        help_text="Name for the single assessment when using single entry mode",
                        max_length=100,
                    ),
                ),
                (
                    "use_default_templates",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-generate assessments from default templates (multiple entry mode only)",
                    ),
                ),
                (
                    "auto_calculate_final_grade",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically calculate final grades from assessments",
                    ),
                ),
                (
                    "default_calculation_method",
                    models.CharField(
                        choices=[
                            ("average", "Simple Average"),
                            ("weighted", "Weighted Average"),
                        ],
                        default="average",
                        help_text="Default calculation method for gradebooks",
                        max_length=20,
                    ),
                ),
                (
                    "require_grade_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Require explicit approval before grades are finalized",
                    ),
                ),
                (
                    "require_grade_review",
                    models.BooleanField(
                        default=True,
                        help_text="Require explicit review before grades are finalized",
                    ),
                ),
                (
                    "display_assessment_on_single_entry",
                    models.BooleanField(
                        default=True,
                        help_text="Display assessment information on single entry grade views",
                    ),
                ),
                (
                    "allow_assessment_delete",
                    models.BooleanField(
                        default=False,
                        help_text="Allow deletion of assessments in multiple entry mode",
                    ),
                ),
                (
                    "allow_assessment_create",
                    models.BooleanField(
                        default=False,
                        help_text="Allow creation of new assessments in multiple entry mode",
                    ),
                ),
                (
                    "allow_assessment_edit",
                    models.BooleanField(
                        default=False,
                        help_text="Allow editing of assessments in multiple entry mode",
                    ),
                ),
                (
                    "use_letter_grades",
                    models.BooleanField(
                        default=True,
                        help_text="Display letter grades alongside percentages",
                    ),
                ),
                (
                    "allow_teacher_override",
                    models.BooleanField(
                        default=True,
                        help_text="Allow teachers to manually adjust calculated grades",
                    ),
                ),
                (
                    "lock_grades_after_semester",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent grade modifications after semester ends",
                    ),
                ),
                (
                    "display_grade_status",
                    models.BooleanField(
                        default=True,
                        help_text="Display the status of grades (e.g., Draft, Finalized)",
                    ),
                ),
                (
                    "cumulative_average_calculation",
                    models.BooleanField(
                        default=False,
                        help_text="cumulative the points earned to calculate the grade average",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about grading configuration",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grading Settings",
                "verbose_name_plural": "Grading Settings",
                "db_table": "grading_settings",
                "ordering": ["grading_style"],
            },
        ),
    ]
