# Generated by Django 5.2.10 on 2026-06-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_grading_settings_promotion_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradingsettings",
            name="allow_mid_year_promotion",
            field=models.BooleanField(
                default=False,
                help_text="Allow mid-year promotion (advance grade without closing the academic year)",
            ),
        ),
        migrations.AlterField(
            model_name="gradingsettings",
            name="allow_year_closure",
            field=models.BooleanField(
                default=True,
                help_text="Allow year-end closure and bulk promotion from the enrollment workspace",
            ),
        ),
        migrations.AlterField(
            model_name="gradingsettings",
            name="mid_year_promotion_min_overall_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Minimum overall average (%) for mid-year promotion",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gradingsettings",
            name="year_closure_min_overall_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Minimum overall grade average (%) required for year-end promotion",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gradingsettings",
            name="year_closure_require_approved_grades",
            field=models.BooleanField(
                default=True,
                help_text="Only approved grades count toward promotion average checks",
            ),
        ),
    ]
