# Generated by Django 5.2.10 on 2026-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_alter_gradingsettings_allow_mid_year_promotion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingsettings",
            name="allow_student_transcript_download",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, eligible students may download official transcripts without submitting a request.",
            ),
        ),
        migrations.AddField(
            model_name="gradingsettings",
            name="student_transcript_download_scope",
            field=models.CharField(
                choices=[
                    ("enrolled", "Currently Enrolled Students"),
                    ("all_active", "All Active Students"),
                ],
                default="enrolled",
                help_text="Which students qualify for self-service transcript download",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gradingsettings",
            name="transcript_download_days",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Number of days a student may download after request approval or admin grant",
            ),
        ),
    ]
