# Generated by Django 5.2.11 on 2026-05-02 00:57

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PayrollItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("allowance", "Allowance"),
                            ("deduction", "Deduction"),
                        ],
                        default="allowance",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("effective_to", models.DateField(blank=True, default=None, null=True)),
                ("notes", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "payroll_item",
                "ordering": ["item_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("payment_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "payroll_period",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default=None, null=True)),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("paid_at", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "payroll_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("biweekly", "Bi-Weekly"),
                            ("weekly", "Weekly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "anchor_date",
                    models.DateField(
                        help_text="Reference date — the first period starts here; subsequent periods step from it."
                    ),
                ),
                (
                    "payment_day_offset",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Days after period_end when payment is made.",
                    ),
                ),
                (
                    "overtime_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.50"), max_digits=4
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pay_schedule",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "unpaid_leave_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "gross_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Frozen detail: per-item allowance/deduction lines and per-rule tax breakdown.",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "payslip",
                "ordering": ["employee__first_name", "employee__last_name"],
            },
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Fixed amount for FLAT, percent (e.g. 10.5) for PERCENTAGE, ignored for FORMULA.",
                        max_digits=12,
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python expression evaluated when calculation_type=FORMULA. Available names: gross, basic, allowances, deductions, taxable_gross, min, max.",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("gross", "Gross Pay"),
                            ("taxable_gross", "Taxable Gross"),
                            ("basic", "Basic Salary"),
                        ],
                        default="gross",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="Lower runs first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("effective_to", models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "tax_rule",
                "ordering": ["priority", "name"],
            },
        ),
    ]
