# Generated by Django 5.2.11 on 2026-05-02 02:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollItemType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional short code, e.g. SSF, LOAN, TRANSPORT.",
                        max_length=50,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("allowance", "Allowance"),
                            ("deduction", "Deduction"),
                        ],
                        default="allowance",
                        max_length=20,
                    ),
                ),
                (
                    "default_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Suggested amount when assigning to an employee. Can be overridden per employee.",
                        max_digits=12,
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system_managed",
                    models.BooleanField(
                        default=False,
                        help_text="System-managed types cannot be deleted; protected fields cannot be edited.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_item_type",
                "ordering": ["item_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="item_type_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Catalog entry. Required for new items; nullable for legacy rows only.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_items",
                to="payroll.payrollitemtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollitemtype",
            constraint=models.UniqueConstraint(
                fields=("name", "item_type"),
                name="payroll_uniq_item_type_name_per_tenant",
            ),
        ),
    ]
