# Generated by Django 5.2.11 on 2026-05-02 02:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_payrollitemtype_payrollitem_item_type_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollitem",
            name="applies_to",
            field=models.CharField(
                choices=[("gross", "Gross Pay"), ("basic", "Basic Salary")],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("flat", "Flat Amount"),
                    ("percentage", "Percentage"),
                    ("formula", "Formula"),
                ],
                default="flat",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="formula",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="value",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Amount for FLAT, percent for PERCENTAGE, ignored for FORMULA.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="payrollitemtype",
            name="applies_to",
            field=models.CharField(
                choices=[("gross", "Gross Pay"), ("basic", "Basic Salary")],
                default="basic",
                help_text="Base used for PERCENTAGE/FORMULA calculations.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payrollitemtype",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("flat", "Flat Amount"),
                    ("percentage", "Percentage"),
                    ("formula", "Formula"),
                ],
                default="flat",
                help_text="How the amount is computed when assigned to an employee.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payrollitemtype",
            name="default_formula",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Default Python expression for FORMULA. Available names: gross, basic, allowances, deductions, taxable_gross, min, max.",
            ),
        ),
        migrations.AddField(
            model_name="payrollitemtype",
            name="default_value",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Suggested value: amount for FLAT, percent for PERCENTAGE, ignored for FORMULA.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="payrollitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cached/legacy resolved amount. Computed from value/formula at payslip time.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="payrollitemtype",
            name="default_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Suggested fallback amount when assigning. Can be overridden per employee.",
                max_digits=12,
            ),
        ),
    ]
