# Generated by Django 5.2.11 on 2026-05-02 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_initial"),
        (
            "payroll",
            "0004_payrollitem_applies_to_payrollitem_calculation_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTaxRuleOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("formula", models.TextField(blank=True, default="")),
                (
                    "applies_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gross", "Gross Pay"),
                            ("taxable_gross", "Taxable Gross"),
                            ("basic", "Basic Salary"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rule_overrides",
                        to="hr.employee",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_overrides",
                        to="payroll.taxrule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_tax_rule_override",
                "ordering": ["rule__priority", "rule__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "rule"),
                        name="payroll_uniq_employee_tax_override",
                    )
                ],
            },
        ),
    ]
