# Generated by Django 5.2.10 on 2026-05-26 15:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_amount_rules(apps, schema_editor):
    PayrollItemType = apps.get_model("payroll", "PayrollItemType")
    PayrollItemTypeRule = apps.get_model("payroll", "PayrollItemTypeRule")
    TaxRule = apps.get_model("payroll", "TaxRule")
    TaxAmountRule = apps.get_model("payroll", "TaxAmountRule")

    for item_type in PayrollItemType.objects.all():
        calc = getattr(item_type, "calculation_type", None) or "flat"
        value = getattr(item_type, "default_value", None)
        if value is None or value == 0:
            legacy = getattr(item_type, "default_amount", None)
            if legacy:
                value = legacy
        PayrollItemTypeRule.objects.create(
            item_type=item_type,
            calculation_type=calc,
            value=value,
            formula=getattr(item_type, "default_formula", "") or "",
            applies_to=getattr(item_type, "applies_to", "basic") or "basic",
            target_salary_min=Decimal("0.00"),
            target_salary_max=Decimal("0.00"),
            target_salary_by="per_period",
            sort_order=0,
        )

    for tax_rule in TaxRule.objects.all():
        TaxAmountRule.objects.create(
            tax_rule=tax_rule,
            calculation_type=getattr(tax_rule, "calculation_type", "percentage") or "percentage",
            value=getattr(tax_rule, "value", None),
            formula=getattr(tax_rule, "formula", "") or "",
            applies_to=getattr(tax_rule, "applies_to", "gross") or "gross",
            target_salary_min=Decimal("0.00"),
            target_salary_max=Decimal("0.00"),
            target_salary_by="per_period",
            sort_order=0,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0005_employeetaxruleoverride"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollItemTypeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        help_text="Flat amount or percentage depending on calculation_type.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python expression when calculation_type=FORMULA. Variables: gross, basic, allowances, deductions, taxable_gross.",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("gross", "Gross Pay"), ("basic", "Basic Salary")],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "target_salary_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Lower salary bound (0 = no lower bound).",
                        max_digits=14,
                    ),
                ),
                (
                    "target_salary_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Upper salary bound (0 = no upper bound).",
                        max_digits=14,
                    ),
                ),
                (
                    "target_salary_by",
                    models.CharField(
                        choices=[("annual", "Annual"), ("per_period", "Per Period")],
                        default="per_period",
                        max_length=20,
                    ),
                ),
                (
                    "salary_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text="Optional cap on the computed amount.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amount_rules",
                        to="payroll.payrollitemtype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_item_type_rule",
                "ordering": ["sort_order", "target_salary_min"],
            },
        ),
        migrations.CreateModel(
            name="TaxAmountRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        help_text="Flat amount or percentage depending on calculation_type.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python expression when calculation_type=FORMULA. Variables: gross, basic, allowances, deductions, taxable_gross.",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("gross", "Gross Pay"),
                            ("taxable_gross", "Taxable Gross"),
                            ("basic", "Basic Salary"),
                        ],
                        default="gross",
                        max_length=20,
                    ),
                ),
                (
                    "target_salary_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Lower salary bound (0 = no lower bound).",
                        max_digits=14,
                    ),
                ),
                (
                    "target_salary_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Upper salary bound (0 = no upper bound).",
                        max_digits=14,
                    ),
                ),
                (
                    "target_salary_by",
                    models.CharField(
                        choices=[("annual", "Annual"), ("per_period", "Per Period")],
                        default="per_period",
                        max_length=20,
                    ),
                ),
                (
                    "salary_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text="Optional cap on the computed amount.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tax_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amount_rules",
                        to="payroll.taxrule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tax_amount_rule",
                "ordering": ["sort_order", "target_salary_min"],
            },
        ),
        migrations.RunPython(migrate_legacy_amount_rules, migrations.RunPython.noop),
        migrations.RemoveField(model_name="payrollitem", name="amount"),
        migrations.RemoveField(model_name="payrollitem", name="applies_to"),
        migrations.RemoveField(model_name="payrollitem", name="calculation_type"),
        migrations.RemoveField(model_name="payrollitem", name="formula"),
        migrations.RemoveField(model_name="payrollitem", name="value"),
        migrations.RemoveField(model_name="payrollitemtype", name="applies_to"),
        migrations.RemoveField(model_name="payrollitemtype", name="calculation_type"),
        migrations.RemoveField(model_name="payrollitemtype", name="default_amount"),
        migrations.RemoveField(model_name="payrollitemtype", name="default_formula"),
        migrations.RemoveField(model_name="payrollitemtype", name="default_value"),
        migrations.RemoveField(model_name="taxrule", name="applies_to"),
        migrations.RemoveField(model_name="taxrule", name="calculation_type"),
        migrations.RemoveField(model_name="taxrule", name="formula"),
        migrations.RemoveField(model_name="taxrule", name="value"),
    ]
