# Generated by Django 5.2.10 on 2026-05-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_employee_teacher_assignments"),
        ("payroll", "0006_amount_rules_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="hr.employee",
            ),
        ),
    ]
