# Generated by Django 5.2.10 on 2026-05-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0012_payrollitem_amount_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeetaxruleoverride",
            name="applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gross", "Gross Pay"),
                    ("taxable_gross", "Taxable Gross"),
                    ("basic", "Basic Salary"),
                    ("annual", "Annual Salary"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payrollitem",
            name="override_applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gross", "Gross Pay"),
                    ("basic", "Basic Salary"),
                    ("annual", "Annual Salary"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payrollitemtyperule",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("gross", "Gross Pay"),
                    ("basic", "Basic Salary"),
                    ("annual", "Annual Salary"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollitemtyperule",
            name="formula",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Python expression when calculation_type=FORMULA. Variables: gross, basic, annual, allowances, deductions, taxable_gross.",
            ),
        ),
        migrations.AlterField(
            model_name="payrollitemtyperule",
            name="target_salary_by",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Salary"),
                    ("per_period", "Monthly / Per Pay Period"),
                ],
                default="per_period",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taxamountrule",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("gross", "Gross Pay"),
                    ("taxable_gross", "Taxable Gross"),
                    ("basic", "Basic Salary"),
                    ("annual", "Annual Salary"),
                ],
                default="gross",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taxamountrule",
            name="formula",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Python expression when calculation_type=FORMULA. Variables: gross, basic, annual, allowances, deductions, taxable_gross.",
            ),
        ),
        migrations.AlterField(
            model_name="taxamountrule",
            name="target_salary_by",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Salary"),
                    ("per_period", "Monthly / Per Pay Period"),
                ],
                default="per_period",
                max_length=20,
            ),
        ),
    ]
