"""Generated by `python manage.py sync_permissions`; do not edit."""


class Permissions:
    class Academics:
        VIEW = "academics.view"
        MANAGE = "academics.manage"
        class Schedule:
            VIEW = "academics.schedule.view"
            MANAGE = "academics.schedule.manage"
        class AcademicYear:
            MANAGE = "academic_year.manage"
            CLOSE = "academic_year.close"

    class Attendance:
        VIEW = "attendance.view"
        TAKE = "attendance.take"
        UPDATE = "attendance.update"
        CORRECT = "attendance.correct"

    class Authorization:
        VIEW = "roles.view"
        CREATE = "roles.create"
        UPDATE = "roles.update"
        DELETE = "roles.delete"
        CLONE = "roles.clone"
        ASSIGN_PERMISSIONS = "roles.assign_permissions"
        ASSIGN_USERS = "roles.assign_users"
        VIEW_AUDIT = "roles.view_audit"

    class Employees:
        VIEW = "employees.view"
        CREATE = "employees.create"
        UPDATE = "employees.update"
        DEACTIVATE = "employees.deactivate"
        class Documents:
            VIEW = "employee.documents.view"
        class Payslip:
            VIEW = "employee.payslip.view"
        class Leave:
            VIEW = "employee.leave.view"
            REQUEST = "employee.leave.request"
        class Benefits:
            VIEW = "employee.benefits.view"
        class Hr:
            VIEW = "hr.view"
            MANAGE = "hr.manage"

    class Finance:
        class Billing:
            VIEW = "billing.view"
            MANAGE = "billing.manage"
        class Transactions:
            VIEW = "finance.transactions.view"
            CREATE = "finance.transactions.create"
            UPDATE = "finance.transactions.update"
            DELETE = "finance.transactions.delete"
            APPROVE = "finance.transactions.approve"
            CANCEL = "finance.transactions.cancel"
            COMPLETE = "finance.transactions.complete"
        class Settings:
            MANAGE = "finance.settings.manage"
        class Accounting:
            VIEW = "accounting.view"
            MANAGE = "accounting.manage"
            CLOSE_PERIOD = "accounting.close_period"

    class Grading:
        VIEW = "grades.view"
        ENTER = "grades.enter"
        REVIEW = "grades.review"
        APPROVE = "grades.approve"
        UNLOCK = "grades.unlock"

    class Notifications:
        VIEW = "notifications.view"
        SEND = "notifications.send"
        SEND_CLASS = "notifications.send_class"
        MANAGE = "notifications.manage"

    class Payroll:
        VIEW = "payroll.view"
        PROCESS = "payroll.process"
        REVIEW = "payroll.review"
        APPROVE = "payroll.approve"
        CONFIGURE = "payroll.configure"

    class Reports:
        class Academic:
            VIEW = "reports.academic.view"
            EXPORT = "reports.academic.export"
        class Finance:
            VIEW = "reports.finance.view"
            EXPORT = "reports.finance.export"
        class Payroll:
            VIEW = "reports.payroll.view"
            EXPORT = "reports.payroll.export"
        class Transcript:
            VIEW = "reports.transcript.view"
            GENERATE = "reports.transcript.generate"

    class Settings:
        class Tenant:
            VIEW = "tenant.settings.view"
            MANAGE = "tenant.settings.manage"
        class Audit:
            VIEW = "audit.view"

    class Students:
        VIEW = "students.view"
        CREATE = "students.create"
        UPDATE = "students.update"
        DELETE = "students.delete"
        ENROLL = "students.enroll"
        PROMOTE = "students.promote"
        TRANSFER = "students.transfer"
        WITHDRAW = "students.withdraw"

    class Users:
        VIEW = "users.view"
        CREATE = "users.create"
        UPDATE = "users.update"
        DEACTIVATE = "users.deactivate"
        class Profile:
            VIEW = "profile.view"
            UPDATE = "profile.update"
