"""Generated by `python manage.py sync_permissions`; do not edit."""


class PlatformPermissions:
    class Billing:
        VIEW = "platform.billing.view"
        MANAGE = "platform.billing.manage"

    class Support:
        ACCESS_TENANT = "platform.support.access_tenant"
        IMPERSONATE = "platform.support.impersonate"

    class System:
        CONFIGURE = "platform.system.configure"

    class Tenants:
        VIEW = "platform.tenants.view"
        MANAGE = "platform.tenants.manage"
        class Users:
            VIEW = "platform.users.view"
        class Audit:
            VIEW = "platform.audit.view"
