from __future__ import annotations

import keyword
import re

from authorization.registry import PermissionRegistry


def _class_name(value: str) -> str:
    name = "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]+", value))
    if not name or name[0].isdigit() or keyword.iskeyword(name):
        raise ValueError(f"Cannot generate class name from {value!r}")
    return name


def _constant_name(value: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9]+", "_", value).strip("_").upper()
    if not name or name[0].isdigit() or keyword.iskeyword(name.lower()):
        raise ValueError(f"Cannot generate constant name from {value!r}")
    return name


def _normalized_namespace(value: str) -> str:
    return value.removesuffix("s")


def _render_tree(tree: dict, *, indent: int) -> list[str]:
    lines: list[str] = []
    prefix = " " * indent
    generated_classes: set[str] = set()
    generated_constants: set[str] = set()
    for name, value in tree.items():
        if isinstance(value, dict):
            generated_name = _class_name(name)
            if generated_name in generated_classes:
                raise ValueError(f"Generated class name collision: {generated_name}")
            generated_classes.add(generated_name)
            lines.append(f"{prefix}class {generated_name}:")
            lines.extend(_render_tree(value, indent=indent + 4))
        else:
            generated_name = _constant_name(name)
            if generated_name in generated_constants:
                raise ValueError(
                    f"Generated constant name collision: {generated_name}"
                )
            generated_constants.add(generated_name)
            lines.append(f'{prefix}{generated_name} = "{value}"')
    return lines


def render_permission_constants(
    registry: PermissionRegistry,
    *,
    root_class: str,
) -> str:
    lines = [
        '"""Generated by `python manage.py sync_permissions`; do not edit."""',
        "",
        "",
        f"class {root_class}:",
    ]

    generated_modules: set[str] = set()
    for module in registry.modules:
        module_class = _class_name(module.module)
        if module_class in generated_modules:
            raise ValueError(f"Generated module class collision: {module_class}")
        generated_modules.add(module_class)
        lines.append(f"    class {module_class}:")
        paths = []
        namespaces: set[str] = set()
        for permission in module.permissions:
            segments = permission.code.split(".")
            if segments[0] == "platform":
                segments = segments[1:]
            namespaces.add(segments[0])
            paths.append((segments, permission.code))

        primary_namespaces = {
            namespace
            for namespace in namespaces
            if _normalized_namespace(namespace)
            == _normalized_namespace(module.module)
        }
        if not primary_namespaces and len(namespaces) == 1:
            primary_namespaces = set(namespaces)

        tree: dict = {}
        for segments, code in paths:
            resource_path = segments[:-1]
            action = segments[-1]
            if resource_path and resource_path[0] in primary_namespaces:
                resource_path = resource_path[1:]
            elif resource_path and resource_path[-1] == module.module:
                resource_path = resource_path[:-1]

            node = tree
            for resource in resource_path:
                existing = node.setdefault(resource, {})
                if not isinstance(existing, dict):
                    raise ValueError(f"Permission constant collision for {code}")
                node = existing
            if action in node:
                raise ValueError(f"Permission constant collision for {code}")
            node[action] = code

        lines.extend(_render_tree(tree, indent=8))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
