# Generated by Django 5.2.11 on 2026-03-05 05:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100, max_digits=8),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "is_calculated",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this assessment should be included in final grade calculations.",
                    ),
                ),
            ],
            options={
                "db_table": "assessment",
                "ordering": ["due_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_single_entry",
                    models.BooleanField(
                        default=False,
                        help_text="True if this assessment type is used for single-entry (final grade only) mode",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DefaultAssessmentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the assessment (e.g., 'Quiz 1', 'Midterm Exam')",
                        max_length=120,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Maximum possible score for this assessment",
                        max_digits=8,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Weight used in weighted grade calculations",
                        max_digits=8,
                    ),
                ),
                (
                    "is_calculated",
                    models.BooleanField(
                        default=True,
                        help_text="Whether assessments created from this template should be included in final grade calculations",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within marking period (lower numbers first)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or instructions for this assessment",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates won't be used for auto-generation",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("marking_period", "Marking Period"),
                            ("exam", "Exam"),
                        ],
                        default="marking_period",
                        help_text="Determines which marking periods receive this assessment. 'marking_period' for regular periods, 'exam' for semester exam periods.",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "assessment_template",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, default=None, null=True)),
                (
                    "needs_correction",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating this grade requires correction/review",
                    ),
                ),
            ],
            options={
                "db_table": "grade",
            },
        ),
        migrations.CreateModel(
            name="GradeBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Algebra I 2025–26 (10A)", max_length=120
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("average", "Simple Average"),
                            ("weighted", "Weighted"),
                            ("cumulative", "Cumulative Points"),
                        ],
                        db_index=True,
                        default="average",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "gradebook",
            },
        ),
        migrations.CreateModel(
            name="GradeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "old_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "new_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=16, null=True)),
                ("new_status", models.CharField(blank=True, max_length=16, null=True)),
                ("old_comment", models.TextField(blank=True, null=True)),
                ("new_comment", models.TextField(blank=True, null=True)),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for the change (e.g., 'Grade correction', 'Re-grading after appeal')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("score", "Score Changed"),
                            ("status", "Status Changed"),
                            ("comment", "Comment Changed"),
                            ("correction", "Correction"),
                            ("bulk", "Bulk Update"),
                        ],
                        default="score",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Grade History",
                "verbose_name_plural": "Grade Histories",
                "db_table": "grade_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "letter",
                    models.CharField(
                        help_text="The letter grade (e.g., A+, A, B+, B, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "min_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum percentage for this letter grade (inclusive)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum percentage for this letter grade (inclusive)",
                        max_digits=5,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for display purposes (lower numbers first)",
                    ),
                ),
            ],
            options={
                "db_table": "grade_letter",
                "ordering": ["order", "-max_percentage"],
            },
        ),
    ]
