# Generated by Django 5.2.11 on 2026-04-21 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HonorCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Display name for the honor category (e.g., 'Principal's List').",
                        max_length=100,
                    ),
                ),
                (
                    "min_average",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum percentage average for this honor (inclusive).",
                        max_digits=5,
                    ),
                ),
                (
                    "max_average",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum percentage average for this honor (inclusive).",
                        max_digits=5,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional badge color (hex or tailwind token) for UI rendering.",
                        max_length=32,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional icon name for UI rendering.",
                        max_length=64,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower numbers first)."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "honor_category",
                "ordering": ["order", "-max_average"],
                "indexes": [
                    models.Index(
                        fields=["min_average", "max_average"],
                        name="honor_categ_min_ave_13ed3a_idx",
                    ),
                    models.Index(fields=["order"], name="honor_categ_order_f7f32b_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("label",), name="unique_honor_label_per_tenant"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("min_average__lte", models.F("max_average"))
                        ),
                        name="honor_category_min_lte_max",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_average__lte", 100), ("min_average__gte", 0)
                        ),
                        name="honor_category_percentage_valid_range",
                    ),
                ],
            },
        ),
    ]
