# Generated by Django 5.2.10 on 2026-05-09 03:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0004_add_unique_constraint_assessments"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assessment",
            name="unique_assessment_per_mp_and_type",
        ),
    ]
