# Generated by Django 5.2.10 on 2026-06-10 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0005_remove_assessment_unique_assessment_per_mp_and_type"),
        (
            "students",
            "0009_rename_historical__student_6f1a2b_idx_historical__student_df688f_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptAccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("student_request", "Student Request"),
                            ("admin_grant", "Admin Grant"),
                        ],
                        default="student_request",
                        max_length=20,
                    ),
                ),
                ("allow_download", models.BooleanField(default=False)),
                ("send_email", models.BooleanField(default=False)),
                (
                    "download_expires_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("student_note", models.TextField(blank=True, default="")),
                ("admin_note", models.TextField(blank=True, default="")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcript_access_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcript_access_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_access_requests",
                        to="students.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transcript_access_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="transcript__student_b12cee_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="transcript__status_70231c_idx",
                    ),
                ],
            },
        ),
    ]
