# Generated by Django 5.2.10 on 2026-07-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0008_normalize_score_condition_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="condition_status",
            field=models.CharField(
                choices=[
                    ("graded", "Graded"),
                    ("no_grade", "No Grade"),
                    ("incomplete", "Incomplete"),
                    ("pending", "Pending"),
                    ("exempt", "Exempt"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
