# Generated by Django 5.2.10 on 2026-07-19 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0009_alter_grade_condition_status"),
        ("grading", "0009_normalize_grade_condition_statuses"),
    ]

    operations = []
