# Generated by Django 5.2 on 2026-08-21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizationAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=100)),
                (
                    "target_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorization_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "authorization_audit_log",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"],
                        name="authz_audit_action_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="authz_audit_target_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "system_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_system_role", models.BooleanField(default=False, editable=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "permission_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_authorization_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "authorization_role",
                "ordering": ("name",),
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("is_system_role", False),
                                ("system_key__isnull", True),
                            )
                            | models.Q(
                                ("is_system_role", True),
                                ("system_key__isnull", False),
                            )
                        ),
                        name="authorization_role_system_key_consistent",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("permission_code", models.CharField(max_length=150)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("own", "Own"),
                            ("assigned", "Assigned"),
                            ("all", "All"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to="authorization.role",
                    ),
                ),
            ],
            options={
                "db_table": "authorization_role_permission",
                "ordering": ("permission_code",),
                "indexes": [
                    models.Index(
                        fields=["role", "permission_code"],
                        name="authz_role_perm_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "permission_code"),
                        name="authorization_unique_role_permission",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "membership_version",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="authorization.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "authorization_tenant_membership",
                "ordering": ("user_id",),
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="authz_member_active_idx",
                    )
                ],
            },
        ),
    ]
