# Generated by Django 5.2.17 on 2026-08-27 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_migrate_legacy_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='shared_role_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='authorization.role'),
        ),
    ]
