# Generated by Django 5.2.17 on 2026-09-28 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_tenant_membership_shared_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_role_id', models.UUIDField(blank=True, null=True)),
                ('role_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='authorization.tenantmembership')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='authorization.role')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('membership', 'role_key'), name='authz_unique_member_role'), models.UniqueConstraint(fields=('membership', 'role'), name='authz_unique_local_assignment'), models.UniqueConstraint(fields=('membership', 'shared_role_id'), name='authz_unique_shared_assignment'), models.CheckConstraint(condition=models.Q(models.Q(('role__isnull', False), ('shared_role_id__isnull', True)), models.Q(('role__isnull', True), ('shared_role_id__isnull', False)), _connector='OR'), name='authz_assignment_one_role')],
            },
        ),
    ]
