# Generated by Django 5.2.10 on 2026-05-31 22:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0009_backfill_transfer_journal_links"),
        ("hr", "0012_remove_employee_tax_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BenefitSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense transaction type used when posting benefit disbursements.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefit_settings",
                        to="accounting.accountingtransactiontype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Benefit Settings",
                "verbose_name_plural": "Employee Benefit Settings",
                "db_table": "employee_benefit_settings",
            },
        ),
        migrations.CreateModel(
            name="BenefitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField(blank=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_benefit_type",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="BenefitRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_number", models.CharField(max_length=50)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="benefit_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefit_requests",
                        to="accounting.accountingbankaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefit_requests",
                        to="accounting.accountingcurrency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "benefit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="employee_benefits.benefittype",
                    ),
                ),
            ],
            options={
                "db_table": "employee_benefit_request",
                "ordering": ["-period_end", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BenefitTypeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="flat",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                ("formula", models.TextField(blank=True)),
                (
                    "target_amount_source",
                    models.CharField(
                        choices=[
                            ("basic_salary", "Basic Salary"),
                            ("gross_pay", "Gross Pay"),
                            ("taxable_income", "Taxable Income"),
                            ("annual_salary", "Annual Salary"),
                        ],
                        default="basic_salary",
                        max_length=50,
                    ),
                ),
                (
                    "target_min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "target_max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "calculation_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("effective_start_date", models.DateField(blank=True, null=True)),
                ("effective_end_date", models.DateField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "benefit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="employee_benefits.benefittype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_benefit_type_rule",
                "ordering": [
                    "benefit_type__priority",
                    "priority",
                    "target_min_amount",
                    "name",
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBenefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_override", models.CharField(blank=True, max_length=120)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Amount"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="flat",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                ("formula", models.TextField(blank=True)),
                (
                    "target_amount_source",
                    models.CharField(
                        choices=[
                            ("basic_salary", "Basic Salary"),
                            ("gross_pay", "Gross Pay"),
                            ("taxable_income", "Taxable Income"),
                            ("annual_salary", "Annual Salary"),
                        ],
                        default="basic_salary",
                        max_length=50,
                    ),
                ),
                (
                    "calculation_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                (
                    "calculation_overridden",
                    models.BooleanField(
                        default=False,
                        help_text="When true, employee-specific calculation replaces catalog rules.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "benefit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="employee_benefits.benefittype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_benefits",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_benefit_assignment",
                "ordering": [
                    "priority",
                    "benefit_type__priority",
                    "benefit_type__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="BenefitRequestLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "computed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "amount_overridden",
                    models.BooleanField(
                        default=False,
                        help_text="When true, final_amount was manually set by finance.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefit_request_lines",
                        to="hr.employee",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="employee_benefits.benefitrequest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_benefit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_lines",
                        to="employee_benefits.employeebenefit",
                    ),
                ),
            ],
            options={
                "db_table": "employee_benefit_request_line",
                "ordering": ["employee__last_name", "employee__first_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="benefittype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("code",),
                name="employee_benefit_uniq_type_code",
            ),
        ),
        migrations.AddIndex(
            model_name="benefitrequest",
            index=models.Index(fields=["status"], name="employee_be_status_3d3061_idx"),
        ),
        migrations.AddIndex(
            model_name="benefitrequest",
            index=models.Index(
                fields=["benefit_type", "period_start", "period_end"],
                name="employee_be_benefit_4d3eca_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="benefitrequest",
            constraint=models.UniqueConstraint(
                fields=("request_number",), name="employee_benefit_uniq_request_number"
            ),
        ),
        migrations.AddIndex(
            model_name="benefittyperule",
            index=models.Index(
                fields=["benefit_type", "is_active"],
                name="employee_be_benefit_5e4ded_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeebenefit",
            index=models.Index(
                fields=["employee", "is_active"], name="employee_be_employe_137fcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeebenefit",
            index=models.Index(
                fields=["start_date", "end_date"], name="employee_be_start_d_9150d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benefitrequestline",
            index=models.Index(
                fields=["request", "employee"], name="employee_be_request_87bcb7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="benefitrequestline",
            constraint=models.UniqueConstraint(
                fields=("request", "employee"),
                name="employee_benefit_uniq_request_employee",
            ),
        ),
    ]
