# Generated by Django 5.2.10 on 2026-05-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_benefits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="benefitsettings",
            name="default_period_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Default period length suggested when finance creates a new request.",
            ),
        ),
        migrations.AddField(
            model_name="benefitsettings",
            name="max_period_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Maximum inclusive length of a benefit request period (in days).",
            ),
        ),
        migrations.AddField(
            model_name="benefitsettings",
            name="min_days_between_requests",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Minimum days after a paid request ends before the next request may start.",
            ),
        ),
    ]
