# Generated by Django 5.2.10 on 2026-06-01 01:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee_benefits", "0002_benefitsettings_default_period_days_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefittype",
            options={"ordering": ["name"]},
        ),
    ]
