# Generated by Django 5.2.10 on 2026-06-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_benefits", "0003_alter_benefittype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="benefitrequest",
            name="paid_table_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
