# Generated by Django 5.2.10 on 2026-06-01 01:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0009_backfill_transfer_journal_links"),
        ("employee_benefits", "0003_alter_benefittype_options"),
        ("hr", "0012_remove_employee_tax_rules"),
        ("payroll_v2", "0013_payroll_settings_schema_repair"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDisbursementRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("payroll", "Payroll"), ("benefit", "Benefit")],
                        max_length=20,
                    ),
                ),
                ("source_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("reverted", "Reverted")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField()),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateField(db_index=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "benefit_type_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "benefit_request_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursement_records",
                        to="employee_benefits.benefitrequestline",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_disbursement_records",
                        to="accounting.accountingcurrency",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursement_records",
                        to="hr.employee",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_disbursement_records",
                        to="accounting.accountingjournalentry",
                    ),
                ),
                (
                    "payroll_employee_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursement_records",
                        to="payroll_v2.payrollemployeeitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_disbursement_record",
                "ordering": ["-payment_date", "-paid_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "payment_date", "status"],
                        name="employee_di_employe_a359f4_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id", "status"],
                        name="employee_di_source__69325e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status", "active"),
                            ("payroll_employee_item__isnull", False),
                        ),
                        fields=("payroll_employee_item",),
                        name="employee_disbursement_uniq_active_payroll_item",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status", "active"),
                            ("benefit_request_line__isnull", False),
                        ),
                        fields=("benefit_request_line",),
                        name="employee_disbursement_uniq_active_benefit_line",
                    ),
                ],
            },
        ),
    ]
