# Generated by Django 5.2.11 on 2026-05-02 00:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("current", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("onhold", "On Hold"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "db_table": "academic_year",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "db_table": "division",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GradeBookScheduleProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "gradebook_schedule_projection",
                "ordering": ["day_of_week", "start_time", "gradebook__name"],
            },
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Grade level number (e.g., 1 for 1st grade)",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "max_class_capacity",
                    models.PositiveIntegerField(
                        default=30, help_text="Maximum number of students in a class"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Level",
                "verbose_name_plural": "Grade Levels",
                "db_table": "grade_level",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="GradeLevelTuitionFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "targeted_student_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tuition fee for the grade level",
                        max_digits=13,
                    ),
                ),
            ],
            options={
                "db_table": "grade_level_tuition_fee",
                "ordering": ["grade_level"],
            },
        ),
        migrations.CreateModel(
            name="MarkingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "short_name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Marking Period",
                "verbose_name_plural": "Marking Periods",
                "db_table": "marking_period",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "period_type",
                    models.CharField(
                        choices=[("class", "Class"), ("recess", "Recess")],
                        default="class",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "period",
            },
        ),
        migrations.CreateModel(
            name="PeriodTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "day_of_week",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Period Time",
                "verbose_name_plural": "Period Times",
                "db_table": "period_time",
                "ordering": ["start_time", "end_time"],
            },
        ),
        migrations.CreateModel(
            name="SchoolCalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("holiday", "Holiday"),
                            ("non_school_day", "Non-school Day"),
                            ("special_day", "Special Day"),
                            ("schedule_override", "Schedule Override"),
                        ],
                        default="holiday",
                        max_length=30,
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[("none", "None"), ("yearly", "Yearly")],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("all_day", models.BooleanField(default=True)),
                ("applies_to_all_sections", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "calendar_event",
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolCalendarEventOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurrence_date", models.DateField()),
            ],
            options={
                "db_table": "calendar_event_occurrence",
                "ordering": ["occurrence_date", "event__name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolCalendarSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operating_days", models.JSONField(default=list)),
                ("timezone", models.CharField(default="UTC", max_length=100)),
            ],
            options={
                "verbose_name": "School Calendar Settings",
                "verbose_name_plural": "School Calendar Settings",
                "db_table": "calendar_settings",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "max_capacity",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "tuition_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "section",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SectionSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "section_schedule",
            },
        ),
        migrations.CreateModel(
            name="SectionSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "section_subject",
                "ordering": ["-active", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="SectionTimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("sort_order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "section_time_slot",
                "ordering": ["day_of_week", "sort_order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "db_table": "semester",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentScheduleProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "student_schedule_projection",
                "ordering": ["student__last_name", "day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "subject",
                "ordering": ["name"],
            },
        ),
    ]
