# Generated by Django 5.2.11 on 2026-03-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="period_type",
            field=models.CharField(
                choices=[("class", "Class"), ("recess", "Recess")],
                default="class",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_schedules",
                to="academics.sectionsubject",
            ),
        ),
    ]
