# Generated by Django 5.2.11 on 2026-03-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_sectiontimeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionschedule",
            name="section_time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_schedules",
                to="academics.sectiontimeslot",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="period_time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_schedules",
                to="academics.periodtime",
            ),
        ),
    ]
