# Generated by Django 5.2.10 on 2026-06-02 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0006_school_calendar_event_times"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="schoolcalendarevent",
            new_name="calendar_ev_recurre_a89d32_idx",
            old_name="calendar_ev_recurre_6a8b0d_idx",
        ),
    ]
