# Generated by Django 5.2.11 on 2026-03-13 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "academics",
            "0007_rename_school_cale_event_t_d0bc87_idx_school_cale_event_t_2908fb_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolCalendarEventOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurrence_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="academics.schoolcalendarevent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "school_calendar_event_occurrence",
                "ordering": ["occurrence_date", "event__name"],
                "indexes": [
                    models.Index(
                        fields=["occurrence_date"],
                        name="school_cale_occurre_fb1402_idx",
                    ),
                    models.Index(
                        fields=["event", "occurrence_date"],
                        name="school_cale_event_i_3ba0eb_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "occurrence_date"),
                        name="uniq_school_calendar_event_occurrence",
                    )
                ],
            },
        ),
    ]
