# Generated by Django 5.2.10 on 2026-06-11 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_academic_year_type_and_optional_dates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicyear",
            options={
                "ordering": ["-start_date", "-name"],
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
            },
        ),
        migrations.RenameIndex(
            model_name="academicyear",
            new_name="academic_ye_year_ty_53d61d_idx",
            old_name="academic_ye_year_ty_8a4b2c_idx",
        ),
    ]
