# Generated by Django 5.2.11 on 2026-03-13 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_schoolcalendareventoccurrence"),
        ("grading", "0002_initial"),
        ("students", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeBookScheduleProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "class_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_projections",
                        to="academics.sectionschedule",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gradebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_projections",
                        to="grading.gradebook",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_schedule_projections",
                        to="academics.period",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_schedule_projections",
                        to="academics.section",
                    ),
                ),
                (
                    "section_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_schedule_projections",
                        to="academics.sectionsubject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_schedule_projections",
                        to="academics.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gradebook_schedule_projection",
                "ordering": ["day_of_week", "start_time", "gradebook__name"],
                "indexes": [
                    models.Index(
                        fields=["gradebook", "day_of_week", "start_time"],
                        name="gradebook_s_gradebo_3afb0b_idx",
                    ),
                    models.Index(
                        fields=["section", "day_of_week", "start_time"],
                        name="gradebook_s_section_24efc9_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("class_schedule", "gradebook"),
                        name="uniq_gradebook_schedule_projection",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentScheduleProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "class_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_projections",
                        to="academics.sectionschedule",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_projections",
                        to="students.enrollment",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_schedule_projections",
                        to="academics.period",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_schedule_projections",
                        to="academics.section",
                    ),
                ),
                (
                    "section_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_schedule_projections",
                        to="academics.sectionsubject",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_projections",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_schedule_projections",
                        to="academics.subject",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_schedule_projection",
                "ordering": ["student__last_name", "day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["student", "day_of_week", "start_time"],
                        name="student_sch_student_6b2f65_idx",
                    ),
                    models.Index(
                        fields=["section", "day_of_week", "start_time"],
                        name="student_sch_section_3c39af_idx",
                    ),
                    models.Index(
                        fields=["enrollment", "day_of_week"],
                        name="student_sch_enrollm_3b1909_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "class_schedule"),
                        name="uniq_student_schedule_projection",
                    )
                ],
            },
        ),
    ]
