# Generated by Django 5.2.11 on 2026-03-15 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0010_rename_school_calendar_tables"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="schoolcalendarevent",
            new_name="calendar_ev_event_t_3e18c8_idx",
            old_name="school_cale_event_t_2908fb_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolcalendarevent",
            new_name="calendar_ev_recurre_effeef_idx",
            old_name="school_cale_recurre_e61db0_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolcalendareventoccurrence",
            new_name="calendar_ev_occurre_96d61e_idx",
            old_name="school_cale_occurre_fb1402_idx",
        ),
        migrations.RenameIndex(
            model_name="schoolcalendareventoccurrence",
            new_name="calendar_ev_event_i_fedac0_idx",
            old_name="school_cale_event_i_3ba0eb_idx",
        ),
    ]
