# Generated by Django 5.2.17 on 2026-09-04 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='website/media')),
                ('display_name', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('purpose', models.CharField(blank=True, default='', max_length=50)),
                ('focal_point', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('standard', 'Standard'), ('news', 'News'), ('events', 'Events'), ('contact', 'Contact'), ('admissions', 'Admissions')], default='standard', max_length=20)),
                ('navigation_visible', models.BooleanField(default=True)),
                ('navigation_order', models.PositiveSmallIntegerField(default=0)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_page',
                'ordering': ['navigation_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteNavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('destination_type', models.CharField(choices=[('page', 'Page'), ('url', 'External URL')], default='page', max_length=10)),
                ('url', models.URLField(blank=True, default='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='school_website.websitenavigationitem')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='school_website.websitepage')),
            ],
            options={
                'db_table': 'website_navigation_item',
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField(unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_revision',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(max_length=50)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('variant', models.CharField(blank=True, default='', max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school_website.websitepage')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_section',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(default='default', editable=False, max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.CharField(choices=[('heritage', 'Heritage'), ('modern', 'Modern'), ('campus', 'Campus'), ('scholar', 'Scholar')], default='modern', max_length=20)),
                ('design_tokens', models.JSONField(blank=True, default=dict)),
                ('seo_defaults', models.JSONField(blank=True, default=dict)),
                ('contact_overrides', models.JSONField(blank=True, default=dict)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('admissions_cta', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('published_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_settings', to='school_website.websiterevision')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Website settings',
                'db_table': 'website_settings',
            },
        ),
        migrations.AddIndex(
            model_name='websitepage',
            index=models.Index(fields=['active', 'navigation_order'], name='website_pag_active_089e21_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesection',
            index=models.Index(fields=['page', 'active', 'position'], name='website_sec_page_id_033d47_idx'),
        ),
        migrations.AddConstraint(
            model_name='websitesection',
            constraint=models.UniqueConstraint(fields=('page', 'position'), name='uniq_website_page_section_position'),
        ),
    ]
