# Generated by Django 5.2.11 on 2026-05-02 00:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountingAccountTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transfer_date", models.DateField()),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=8, default=1, max_digits=18),
                ),
                (
                    "to_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount received in to_currency",
                        max_digits=18,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Account Transfer",
                "verbose_name_plural": "Account Transfers",
                "db_table": "accounting_account_transfer",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountingARSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_billed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_concessions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid_in_full", "Paid in Full"),
                            ("on_time", "On Time"),
                            ("overdue", "Overdue"),
                            ("not_billed", "Not Billed"),
                        ],
                        default="not_billed",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AR Snapshot",
                "verbose_name_plural": "AR Snapshots",
                "db_table": "accounting_ar_snapshot",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="AccountingBankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=50, unique=True)),
                ("account_name", models.CharField(max_length=255)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("opening_balance_date", models.DateField(blank=True, null=True)),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated from approved transactions",
                        max_digits=18,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "db_table": "accounting_bank_account",
                "ordering": ["account_number"],
            },
        ),
        migrations.CreateModel(
            name="AccountingCashTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField()),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=8, default=1, max_digits=18),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in base currency",
                        max_digits=18,
                    ),
                ),
                (
                    "payer_payee",
                    models.CharField(
                        blank=True, help_text="Who paid/received", max_length=255
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Audit trail: original document/invoice reference",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Transaction",
                "verbose_name_plural": "Cash Transactions",
                "db_table": "accounting_cash_transaction",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountingConcession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concession_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("flat", "Flat Amount")],
                        max_length=20,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("entire_bill", "Entire Bill"),
                            ("tuition", "Tuition Only"),
                            ("other_fees", "Other Fees Only"),
                        ],
                        default="entire_bill",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or flat amount",
                        max_digits=18,
                    ),
                ),
                (
                    "computed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Computed concession amount",
                        max_digits=18,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Concession",
                "verbose_name_plural": "Concessions",
                "db_table": "accounting_concession",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountingCurrency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("symbol", models.CharField(max_length=10)),
                (
                    "is_base_currency",
                    models.BooleanField(
                        default=False, help_text="Primary currency for this tenant"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("decimal_places", models.PositiveIntegerField(default=2)),
            ],
            options={
                "verbose_name": "Accounting Currency",
                "verbose_name_plural": "Accounting Currencies",
                "db_table": "accounting_currency",
                "ordering": ["-is_base_currency", "code"],
            },
        ),
        migrations.CreateModel(
            name="AccountingExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Accounting Exchange Rate",
                "verbose_name_plural": "Accounting Exchange Rates",
                "db_table": "accounting_exchange_rate",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountingExpenseRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplies", "Supplies"),
                            ("utilities", "Utilities"),
                            ("maintenance", "Maintenance"),
                            ("professional_fees", "Professional Fees"),
                            ("travel", "Travel"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("expense_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("posted", "Posted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Expense Record",
                "verbose_name_plural": "Expense Records",
                "db_table": "accounting_expense_record",
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountingFeeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tuition", "Tuition"),
                            ("general", "General Fee"),
                            ("activity", "Activity Fee"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Fee Item",
                "verbose_name_plural": "Fee Items",
                "db_table": "accounting_fee_item",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountingFeeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., new, returning, transfer",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                "verbose_name": "Fee Rate",
                "verbose_name_plural": "Fee Rates",
                "db_table": "accounting_fee_rate",
                "ordering": ["academic_year", "fee_item"],
            },
        ),
        migrations.CreateModel(
            name="AccountingInstallmentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("due_date", models.DateField()),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of total bill (0-100)",
                        max_digits=5,
                    ),
                ),
                ("grace_days", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Installment Line",
                "verbose_name_plural": "Installment Lines",
                "db_table": "accounting_installment_line",
                "ordering": ["installment_plan", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="AccountingInstallmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Installment Plan",
                "verbose_name_plural": "Installment Plans",
                "db_table": "accounting_installment_plan",
                "ordering": ["academic_year", "name"],
            },
        ),
        migrations.CreateModel(
            name="AccountingJournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("posting_date", models.DateField()),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("student_payment", "Student Payment"),
                            ("payroll", "Payroll"),
                            ("bank_transfer", "Bank Transfer"),
                            ("concession", "Concession"),
                            ("fee_adjustment", "Fee Adjustment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "posted_by",
                    models.CharField(
                        blank=True,
                        help_text="User or system that posted this entry",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Audit trail: original transaction/document reference",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "db_table": "accounting_journal_entry",
                "ordering": ["-posting_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountingJournalLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Debit amount in transaction currency",
                        max_digits=18,
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Credit amount in transaction currency",
                        max_digits=18,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8,
                        default=1,
                        help_text="Exchange rate to base currency",
                        max_digits=18,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Converted amount in base currency",
                        max_digits=18,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("line_sequence", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Journal Line",
                "verbose_name_plural": "Journal Lines",
                "db_table": "accounting_journal_line",
                "ordering": ["journal_entry", "line_sequence"],
            },
        ),
        migrations.CreateModel(
            name="AccountingLedgerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("income", "Income"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Grouping for reports (e.g., Revenue, COGS)",
                        max_length=100,
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=6
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_header",
                    models.BooleanField(
                        default=False, help_text="Header account (no direct postings)"
                    ),
                ),
                (
                    "is_system_managed",
                    models.BooleanField(
                        default=False,
                        help_text="System-managed accounts are seeded/maintained by the platform (e.g., transfer clearing accounts) and cannot be edited or deleted by users.",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ledger Account",
                "verbose_name_plural": "Ledger Accounts",
                "db_table": "accounting_ledger_account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountingPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "accounting_payment_method",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccountingPayrollPostingBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("posting_date", models.DateField()),
                (
                    "batch_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "idempotent_key",
                    models.CharField(
                        help_text="Unique idempotent key to prevent duplicate postings",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("posted_by", models.CharField(blank=True, max_length=100, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payroll Posting Batch",
                "verbose_name_plural": "Payroll Posting Batches",
                "db_table": "accounting_payroll_posting_batch",
                "ordering": ["-posting_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountingPayrollPostingLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("advance", "Advance"),
                            ("deduction", "Deduction"),
                            ("tax", "Tax"),
                            ("benefit", "Benefit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Payroll Posting Line",
                "verbose_name_plural": "Payroll Posting Lines",
                "db_table": "accounting_payroll_posting_line",
                "ordering": ["posting_batch", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountingStudentBill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField()),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "concession_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Student Bill",
                "verbose_name_plural": "Student Bills",
                "db_table": "accounting_student_bill",
                "ordering": ["-bill_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountingStudentBillLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("unit_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("line_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("line_sequence", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Student Bill Line",
                "verbose_name_plural": "Student Bill Lines",
                "db_table": "accounting_student_bill_line",
                "ordering": ["student_bill", "line_sequence"],
            },
        ),
        migrations.CreateModel(
            name="AccountingStudentPaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("allocation_date", models.DateField()),
            ],
            options={
                "verbose_name": "Student Payment Allocation",
                "verbose_name_plural": "Student Payment Allocations",
                "db_table": "accounting_student_payment_allocation",
                "ordering": ["-allocation_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountingTaxCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("vat", "VAT"),
                            ("gst", "GST"),
                            ("payroll_tax", "Payroll Tax"),
                            ("corporate_tax", "Corporate Tax"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate as percentage",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tax Code",
                "verbose_name_plural": "Tax Codes",
                "db_table": "accounting_tax_code",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountingTaxRemittance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("filed", "Filed"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("total_due", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("filing_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tax Remittance",
                "verbose_name_plural": "Tax Remittances",
                "db_table": "accounting_tax_remittance",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="AccountingTransactionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "transaction_category",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "auto_manage_ledger_account",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, the system creates and keeps a chart-of-accounts entry in sync with this transaction type.",
                    ),
                ),
                (
                    "is_system_managed",
                    models.BooleanField(
                        default=False,
                        help_text="When true, this transaction type is created and maintained by the platform and cannot be edited or deleted from the UI.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Transaction Type",
                "verbose_name_plural": "Transaction Types",
                "db_table": "accounting_transaction_type",
                "ordering": ["name"],
            },
        ),
    ]
