# Generated by Django 5.2.11 on 2026-03-27 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_cash_posting_account_mappings"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accountingcashtransaction",
            new_name="accounting__transac_b65014_idx",
            old_name="accounting__transac_type_status_idx",
        ),
    ]
