# Generated by Django 5.2.11 on 2026-03-30 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0006_seed_accounting_from_finance_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingbankaccount",
            name="ledger_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Ledger cash/bank account used during posting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_accounts",
                to="accounting.accountingledgeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="accountingcashtransaction",
            name="ledger_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional override account; if empty, use transaction type default",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_transactions",
                to="accounting.accountingledgeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="accountingtransactiontype",
            name="default_ledger_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default income/expense ledger account used for auto-posting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_transaction_types",
                to="accounting.accountingledgeraccount",
            ),
        ),
    ]
