# Generated by Django 5.2.10 on 2026-05-29 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0006_remove_accountingpayrollpostingbatch_payroll_run"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_deductions_payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Liability account credited for non-tax payroll deductions.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_settings_payroll_deductions_payable",
                        to="accounting.accountingledgeraccount",
                    ),
                ),
                (
                    "payroll_tax_payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Liability account credited for payroll tax withholdings.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_settings_payroll_tax_payable",
                        to="accounting.accountingledgeraccount",
                    ),
                ),
                (
                    "salary_expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense account debited when payroll is posted to the ledger.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_settings_salary_expense",
                        to="accounting.accountingledgeraccount",
                    ),
                ),
                (
                    "transfer_clearing_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset clearing account used for account-to-account bank transfers.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_settings_transfer_clearing",
                        to="accounting.accountingledgeraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Settings",
                "verbose_name_plural": "Accounting Settings",
                "db_table": "accounting_settings",
            },
        ),
    ]
