# Generated by Django 5.2.11 on 2026-04-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0007_alter_accountingbankaccount_ledger_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingcashtransaction",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Posted journal entry — deleting the journal entry also deletes this transaction",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_transactions",
                to="accounting.accountingjournalentry",
            ),
        ),
    ]
