# Generated by Django 5.2.11 on 2026-08-04 17:42

from django.db import migrations, models


def backfill_completed_for_posted_approved(apps, schema_editor):
    AccountingCashTransaction = apps.get_model("accounting", "AccountingCashTransaction")
    queryset = AccountingCashTransaction.objects.filter(
        status="approved",
        journal_entry__isnull=False,
    )

    for row in queryset.iterator(chunk_size=1000):
        row.status = "completed"
        row.completed_by = row.approved_by
        row.completed_at = row.approved_at or row.updated_at
        row.save(update_fields=["status", "completed_by", "completed_at", "updated_at"])


def noop_reverse(apps, schema_editor):
    # Intentionally no-op: migration is forward-only to preserve completion history.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0010_accountingsettings_student_refund_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingcashtransaction",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountingcashtransaction",
            name="completed_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="accountingcashtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_completed_for_posted_approved,
            reverse_code=noop_reverse,
        ),
    ]
