# Generated by Django 5.2.11 on 2026-08-06 20:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0013_cash_and_journal_notes"),
        ("hr", "0012_remove_employee_tax_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingsettings",
            name="default_expense_bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default bank account preselected for expense disbursements.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounting_settings_default_expense",
                to="accounting.accountingbankaccount",
            ),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="default_payroll_bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default bank account preselected for payroll disbursements.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounting_settings_default_payroll",
                to="accounting.accountingbankaccount",
            ),
        ),
        migrations.CreateModel(
            name="AccountingBankBalanceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "limit_mode",
                    models.CharField(
                        choices=[
                            ("fixed_amount", "Fixed Amount"),
                            ("percent_revenue", "Percentage of Total Revenue"),
                        ],
                        default="fixed_amount",
                        max_length=32,
                    ),
                ),
                (
                    "fixed_maximum_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "revenue_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of total revenue when limit_mode=percent_revenue.",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "revenue_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        default="monthly",
                        max_length=32,
                    ),
                ),
                (
                    "behavior",
                    models.CharField(
                        choices=[
                            ("block", "Block Transaction"),
                            ("warn", "Allow with Warning"),
                        ],
                        default="block",
                        max_length=16,
                    ),
                ),
                ("enable_email_alerts", models.BooleanField(default=False)),
                (
                    "alert_trigger",
                    models.CharField(
                        choices=[
                            ("before", "Before Maximum"),
                            ("at_maximum", "At Maximum"),
                            ("both", "Before and At Maximum"),
                        ],
                        default="both",
                        max_length=24,
                    ),
                ),
                (
                    "alert_threshold_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("90.00"), max_digits=7
                    ),
                ),
                ("use_default_email_template", models.BooleanField(default=True)),
                ("email_subject_template", models.TextField(blank=True, default="")),
                ("email_body_template", models.TextField(blank=True, default="")),
                (
                    "alert_recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accounting_balance_alert_rules",
                        to="hr.employee",
                    ),
                ),
                (
                    "bank_accounts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="balance_rules",
                        to="accounting.accountingbankaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Bank Balance Rule",
                "verbose_name_plural": "Accounting Bank Balance Rules",
                "db_table": "accounting_bank_balance_rule",
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountingSpendableAllocationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Spendable Allocation", max_length=150),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "limit_mode",
                    models.CharField(
                        choices=[
                            ("fixed_amount", "Fixed Amount"),
                            ("percent_revenue", "Percentage of Total Revenue"),
                        ],
                        default="fixed_amount",
                        max_length=32,
                    ),
                ),
                (
                    "fixed_allocation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "revenue_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "revenue_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("all_time", "All Time"),
                        ],
                        default="monthly",
                        max_length=32,
                    ),
                ),
                (
                    "behavior",
                    models.CharField(
                        choices=[
                            ("block", "Block Transaction"),
                            ("warn", "Allow with Warning"),
                        ],
                        default="block",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Spendable Allocation Rule",
                "verbose_name_plural": "Accounting Spendable Allocation Rules",
                "db_table": "accounting_spendable_allocation_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountingRuleThresholdState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threshold_percentage",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("is_above_threshold", models.BooleanField(default=False)),
                (
                    "last_triggered_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "balance_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold_states",
                        to="accounting.accountingbankbalancerule",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold_states",
                        to="accounting.accountingbankaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Rule Threshold State",
                "verbose_name_plural": "Accounting Rule Threshold States",
                "db_table": "accounting_rule_threshold_state",
                "indexes": [
                    models.Index(
                        fields=["balance_rule", "bank_account"],
                        name="accounting__balance_c70e2f_idx",
                    ),
                    models.Index(
                        fields=["last_triggered_at"],
                        name="accounting__last_tr_346a57_idx",
                    ),
                ],
                "unique_together": {
                    ("balance_rule", "bank_account", "threshold_percentage")
                },
            },
        ),
    ]
