# Generated by Django 5.2.10 on 2026-08-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0015_bank_rule_notification_trigger_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingbankbalancerule",
            name="notification_channel",
            field=models.CharField(
                choices=[("in_app", "In-App"), ("email", "Email"), ("both", "Both")],
                default="in_app",
                max_length=16,
            ),
        ),
    ]
