# Generated by Django 5.2.10 on 2026-06-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_banner_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("grade_published", "Grade published"),
                    ("payment_due_reminder", "Payment due reminder"),
                    ("attendance_absent", "Attendance absent"),
                    ("transcript_requested", "Transcript requested"),
                    ("transcript_approved", "Transcript approved"),
                    ("transcript_denied", "Transcript denied"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
